# Pre-processing:
## Generating config files

In [1]:
import numpy as np 
import pandas as pd
import os

In [2]:
#connect to the server and copy the path to your sequencing data
fp = '/net/bmc-lab2/data/lab/sanchezrivera/hcevasco/DASIT/251212San/'
k = os.listdir(fp)

#might need to change the 'D24' depending on file naming
k = [i for i in k if i[:3]=='D25'] 

# ammended Sam's code because we had data split across 2 lanes so this uses the concatenated R1 and R2 files we already made
folder_name = []
f1 = []
f2 = []
for ii in range(len(k)):
    j = os.listdir(f'{fp}/{k[ii]}')

    r1 = [i for i in j if i.endswith('_R1_sequence.fastq')]
    r2 = [i for i in j if i.endswith('_R2_sequence.fastq')]

    if len(r1) != 1 or len(r2) != 1:
        raise ValueError(f'Unexpected FASTQs in {k[ii]}: {j}')

    f1.append(f'./{k[ii]}/{r1[0]}')
    f2.append(f'./{k[ii]}/{r2[0]}')
    folder_name.append(k[ii] + '_guide_split_BARCODES')

config_df = pd.DataFrame(dict(zip(['ArrayTaskID', 'R1_FILE', 'R2_FILE', 'folder_name'], [list(range(1, len(f1)+1)), f1, f2, folder_name])))
config_df.to_csv('sensor_extraction_fastq_split_config_HC_DASIT.txt', index=False, sep = ' ')

ValueError: Unexpected FASTQs in D25-251041_guide_split_BARCODES: ['gRNA_1.fastq', 'gRNA_2.fastq', 'gRNA_3.fastq', 'gRNA_67.fastq', 'gRNA_84.fastq', 'gRNA_85.fastq', 'gRNA_95.fastq', 'gRNA_120.fastq', 'gRNA_121.fastq', 'gRNA_122.fastq', 'gRNA_196.fastq', 'gRNA_197.fastq', 'gRNA_198.fastq', 'gRNA_235.fastq', 'gRNA_283.fastq', 'gRNA_284.fastq', 'gRNA_285.fastq', 'gRNA_292.fastq', 'gRNA_293.fastq', 'gRNA_299.fastq', 'gRNA_300.fastq', 'gRNA_497.fastq', 'gRNA_498.fastq', 'gRNA_528.fastq', 'gRNA_594.fastq', 'gRNA_671.fastq', 'gRNA_736.fastq', 'gRNA_740.fastq', 'gRNA_741.fastq', 'gRNA_767.fastq', 'gRNA_768.fastq', 'gRNA_769.fastq', 'gRNA_806.fastq', 'gRNA_807.fastq', 'gRNA_828.fastq', 'gRNA_829.fastq', 'gRNA_830.fastq', 'gRNA_831.fastq', 'gRNA_871.fastq', 'gRNA_895.fastq', 'gRNA_896.fastq', 'gRNA_901.fastq', 'gRNA_974.fastq', 'gRNA_978.fastq', 'gRNA_979.fastq', 'gRNA_992.fastq', 'gRNA_993.fastq', 'gRNA_999.fastq', 'gRNA_1000.fastq', 'gRNA_1008.fastq', 'gRNA_1009.fastq', 'gRNA_1010.fastq', 'gRNA_1011.fastq', 'gRNA_1014.fastq', 'gRNA_1017.fastq', 'gRNA_1018.fastq', 'gRNA_1035.fastq', 'gRNA_1036.fastq', 'gRNA_1045.fastq', 'gRNA_1046.fastq', 'gRNA_1047.fastq', 'gRNA_1048.fastq', 'gRNA_1049.fastq', 'gRNA_1056.fastq', 'gRNA_1065.fastq', 'gRNA_1066.fastq', 'gRNA_1069.fastq', 'gRNA_1082.fastq', 'gRNA_1083.fastq', 'gRNA_1095.fastq', 'gRNA_1109.fastq', 'gRNA_1121.fastq', 'gRNA_1122.fastq', 'gRNA_1127.fastq', 'gRNA_1145.fastq', 'gRNA_1146.fastq', 'gRNA_1148.fastq', 'gRNA_1149.fastq', 'gRNA_1150.fastq', 'gRNA_1151.fastq', 'gRNA_1281.fastq', 'gRNA_1282.fastq', 'gRNA_1283.fastq', 'gRNA_1284.fastq', 'gRNA_1285.fastq', 'gRNA_1313.fastq', 'gRNA_1314.fastq', 'gRNA_1317.fastq', 'gRNA_1318.fastq', 'gRNA_1321.fastq', 'gRNA_1322.fastq', 'gRNA_1337.fastq', 'gRNA_1338.fastq', 'gRNA_1339.fastq', 'gRNA_1340.fastq', 'gRNA_1341.fastq', 'gRNA_1342.fastq', 'gRNA_1343.fastq', 'gRNA_1361.fastq', 'gRNA_1362.fastq', 'gRNA_1373.fastq', 'gRNA_1374.fastq', 'gRNA_1375.fastq', 'gRNA_1376.fastq', 'gRNA_1377.fastq', 'gRNA_1378.fastq', 'gRNA_1379.fastq', 'gRNA_1380.fastq', 'gRNA_1381.fastq', 'gRNA_1382.fastq', 'gRNA_1383.fastq', 'gRNA_1384.fastq', 'gRNA_1385.fastq', 'gRNA_1406.fastq', 'gRNA_1407.fastq', 'gRNA_1459.fastq', 'gRNA_1460.fastq', 'gRNA_1461.fastq', 'gRNA_1463.fastq', 'gRNA_1491.fastq', 'gRNA_1492.fastq', 'gRNA_1545.fastq', 'gRNA_1548.fastq', 'gRNA_1549.fastq', 'gRNA_1550.fastq', 'gRNA_1551.fastq', 'gRNA_1552.fastq', 'gRNA_1558.fastq', 'gRNA_1559.fastq', 'gRNA_1569.fastq', 'gRNA_1570.fastq', 'gRNA_1573.fastq', 'gRNA_1583.fastq', 'gRNA_1588.fastq', 'gRNA_1590.fastq', 'gRNA_1591.fastq', 'gRNA_1592.fastq', 'gRNA_1696.fastq', 'gRNA_1725.fastq', 'gRNA_1726.fastq', 'gRNA_1733.fastq', 'gRNA_1738.fastq', 'gRNA_1817.fastq', 'gRNA_1848.fastq', 'gRNA_1855.fastq', 'gRNA_1857.fastq', 'gRNA_1858.fastq', 'gRNA_1871.fastq', 'gRNA_1875.fastq', 'gRNA_1876.fastq', 'gRNA_1882.fastq', 'gRNA_1898.fastq', 'gRNA_1901.fastq', 'gRNA_1904.fastq', 'gRNA_1905.fastq', 'gRNA_1906.fastq', 'gRNA_1925.fastq', 'gRNA_1928.fastq', 'gRNA_1929.fastq', 'gRNA_1930.fastq', 'gRNA_1953.fastq', 'gRNA_1961.fastq', 'gRNA_1962.fastq', 'gRNA_1963.fastq', 'gRNA_1972.fastq', 'gRNA_1973.fastq', 'gRNA_1977.fastq', 'gRNA_1978.fastq', 'gRNA_1980.fastq', 'gRNA_1981.fastq', 'gRNA_1983.fastq', 'gRNA_1984.fastq', 'gRNA_1985.fastq', 'gRNA_1989.fastq', 'gRNA_1994.fastq', 'gRNA_1995.fastq', 'gRNA_1996.fastq', 'gRNA_2011.fastq', 'gRNA_2012.fastq', 'gRNA_2043.fastq', 'gRNA_2044.fastq', 'gRNA_2105.fastq', 'gRNA_2133.fastq', 'gRNA_2134.fastq', 'gRNA_2135.fastq', 'gRNA_2154.fastq', 'gRNA_2202.fastq', 'gRNA_2203.fastq', 'gRNA_2215.fastq', 'gRNA_2234.fastq', 'gRNA_2240.fastq', 'gRNA_2265.fastq', 'gRNA_2268.fastq', 'gRNA_2269.fastq', 'gRNA_2270.fastq', 'gRNA_2281.fastq', 'gRNA_2284.fastq', 'gRNA_2285.fastq', 'gRNA_2292.fastq', 'gRNA_2293.fastq', 'gRNA_2294.fastq', 'gRNA_2297.fastq', 'gRNA_2298.fastq', 'gRNA_2316.fastq', 'gRNA_2326.fastq', 'gRNA_2384.fastq', 'gRNA_2385.fastq', 'gRNA_2386.fastq', 'gRNA_2387.fastq', 'gRNA_2388.fastq', 'gRNA_2398.fastq', 'gRNA_2399.fastq', 'gRNA_2401.fastq', 'gRNA_2415.fastq', 'gRNA_2416.fastq', 'gRNA_2417.fastq', 'gRNA_2440.fastq', 'gRNA_2441.fastq', 'gRNA_2445.fastq', 'gRNA_2446.fastq', 'gRNA_2457.fastq', 'gRNA_2458.fastq', 'gRNA_2466.fastq', 'gRNA_2472.fastq', 'gRNA_2473.fastq', 'gRNA_2474.fastq', 'gRNA_2494.fastq', 'gRNA_2521.fastq', 'gRNA_2526.fastq', 'gRNA_2527.fastq', 'gRNA_2568.fastq', 'gRNA_2569.fastq', 'gRNA_2620.fastq', 'gRNA_2645.fastq', 'gRNA_2648.fastq', 'gRNA_2649.fastq', 'gRNA_2657.fastq', 'gRNA_2658.fastq', 'gRNA_2671.fastq', 'gRNA_2679.fastq', 'gRNA_2683.fastq', 'gRNA_2684.fastq', 'gRNA_2691.fastq', 'gRNA_2692.fastq', 'gRNA_2693.fastq', 'gRNA_2694.fastq', 'gRNA_2696.fastq', 'gRNA_2697.fastq', 'gRNA_2698.fastq', 'gRNA_2702.fastq', 'gRNA_2703.fastq', 'gRNA_2723.fastq', 'gRNA_2724.fastq', 'gRNA_2739.fastq', 'gRNA_2747.fastq', 'gRNA_2748.fastq', 'gRNA_2775.fastq', 'gRNA_2776.fastq', 'gRNA_2777.fastq', 'gRNA_2778.fastq', 'gRNA_2784.fastq', 'gRNA_2785.fastq', 'gRNA_2794.fastq', 'gRNA_2802.fastq', 'gRNA_2803.fastq', 'gRNA_2810.fastq', 'gRNA_2842.fastq', 'gRNA_2891.fastq', 'gRNA_2892.fastq', 'gRNA_2914.fastq', 'gRNA_2917.fastq', 'gRNA_2918.fastq', 'gRNA_2947.fastq', 'gRNA_2949.fastq', 'gRNA_2950.fastq', 'gRNA_2951.fastq', 'gRNA_2952.fastq', 'gRNA_2956.fastq', 'gRNA_2957.fastq', 'gRNA_2963.fastq', 'gRNA_2971.fastq', 'gRNA_2975.fastq', 'gRNA_2981.fastq', 'gRNA_3011.fastq', 'gRNA_3012.fastq', 'gRNA_3021.fastq', 'gRNA_3025.fastq', 'gRNA_3026.fastq', 'gRNA_3030.fastq', 'gRNA_3031.fastq', 'gRNA_3032.fastq', 'gRNA_3033.fastq', 'gRNA_3034.fastq', 'gRNA_3046.fastq', 'gRNA_3047.fastq', 'gRNA_3048.fastq', 'gRNA_3056.fastq', 'gRNA_3060.fastq', 'gRNA_3061.fastq', 'gRNA_3084.fastq', 'gRNA_3085.fastq', 'gRNA_3086.fastq', 'gRNA_3089.fastq', 'gRNA_3106.fastq', 'gRNA_3107.fastq', 'gRNA_3114.fastq', 'gRNA_3115.fastq', 'gRNA_3142.fastq', 'gRNA_3143.fastq', 'gRNA_3220.fastq', 'gRNA_3221.fastq', 'gRNA_3224.fastq', 'gRNA_3225.fastq', 'gRNA_3249.fastq', 'gRNA_3250.fastq', 'gRNA_3251.fastq', 'gRNA_3283.fastq', 'gRNA_3313.fastq', 'gRNA_3314.fastq', 'gRNA_3340.fastq', 'gRNA_3341.fastq', 'gRNA_3383.fastq', 'gRNA_3415.fastq', 'gRNA_3416.fastq', 'gRNA_3469.fastq', 'gRNA_3470.fastq', 'gRNA_3471.fastq', 'gRNA_3502.fastq', 'gRNA_3503.fastq', 'gRNA_3510.fastq', 'gRNA_3511.fastq', 'gRNA_3515.fastq', 'gRNA_3516.fastq', 'gRNA_3517.fastq', 'gRNA_3518.fastq', 'gRNA_3522.fastq', 'gRNA_3523.fastq', 'gRNA_3524.fastq', 'gRNA_3525.fastq', 'gRNA_3543.fastq', 'gRNA_3544.fastq', 'gRNA_3545.fastq', 'gRNA_3569.fastq', 'gRNA_3570.fastq', 'gRNA_3571.fastq', 'gRNA_3572.fastq', 'gRNA_3577.fastq', 'gRNA_3578.fastq', 'gRNA_3579.fastq', 'gRNA_3580.fastq', 'gRNA_3626.fastq', 'gRNA_3666.fastq', 'gRNA_3676.fastq', 'gRNA_3677.fastq', 'gRNA_3679.fastq', 'gRNA_3680.fastq', 'gRNA_3681.fastq', 'gRNA_3682.fastq', 'gRNA_3685.fastq', 'gRNA_3686.fastq', 'gRNA_3692.fastq', 'gRNA_3693.fastq', 'gRNA_3694.fastq', 'gRNA_3698.fastq', 'gRNA_3699.fastq', 'gRNA_3703.fastq', 'gRNA_3704.fastq', 'gRNA_3705.fastq', 'gRNA_3711.fastq', 'gRNA_3712.fastq', 'gRNA_3754.fastq', 'gRNA_3755.fastq', 'gRNA_3804.fastq', 'gRNA_3805.fastq', 'gRNA_3806.fastq', 'gRNA_3838.fastq', 'gRNA_3842.fastq', 'gRNA_3843.fastq', 'gRNA_3861.fastq', 'gRNA_3868.fastq', 'gRNA_3905.fastq', 'gRNA_3906.fastq', 'gRNA_3907.fastq', 'gRNA_3908.fastq', 'gRNA_3909.fastq', 'gRNA_3923.fastq', 'gRNA_3924.fastq', 'gRNA_3925.fastq', 'gRNA_3926.fastq', 'gRNA_3964.fastq', 'gRNA_3975.fastq', 'gRNA_3976.fastq', 'gRNA_3985.fastq', 'gRNA_3995.fastq', 'gRNA_3996.fastq', 'gRNA_4012.fastq', 'gRNA_4021.fastq', 'gRNA_4032.fastq', 'gRNA_4033.fastq', 'gRNA_4104.fastq', 'gRNA_4105.fastq', 'gRNA_4106.fastq', 'gRNA_4111.fastq', 'gRNA_4116.fastq', 'gRNA_4117.fastq', 'gRNA_4118.fastq', 'gRNA_4119.fastq', 'gRNA_4141.fastq', 'gRNA_4142.fastq', 'gRNA_4143.fastq', 'gRNA_4144.fastq', 'gRNA_4191.fastq', 'gRNA_4192.fastq', 'gRNA_4193.fastq', 'gRNA_4194.fastq', 'gRNA_4195.fastq', 'gRNA_4213.fastq', 'gRNA_4225.fastq', 'gRNA_4226.fastq', 'gRNA_4246.fastq', 'gRNA_4247.fastq', 'gRNA_4248.fastq', 'gRNA_4261.fastq', 'gRNA_4262.fastq', 'gRNA_4263.fastq', 'gRNA_4302.fastq', 'gRNA_4303.fastq', 'gRNA_4304.fastq', 'gRNA_4329.fastq', 'gRNA_4330.fastq', 'gRNA_4331.fastq', 'gRNA_4357.fastq', 'gRNA_4419.fastq', 'gRNA_4421.fastq', 'gRNA_4422.fastq', 'gRNA_4440.fastq', 'gRNA_4447.fastq', 'gRNA_4459.fastq', 'gRNA_4460.fastq', 'gRNA_4461.fastq', 'gRNA_4547.fastq', 'gRNA_4548.fastq', 'gRNA_4549.fastq', 'gRNA_4550.fastq', 'gRNA_4562.fastq', 'gRNA_4567.fastq', 'gRNA_4577.fastq', 'gRNA_4578.fastq', 'gRNA_4586.fastq', 'gRNA_4587.fastq', 'gRNA_4589.fastq', 'gRNA_4590.fastq', 'gRNA_4591.fastq', 'gRNA_4621.fastq', 'gRNA_4622.fastq', 'gRNA_4627.fastq', 'gRNA_4628.fastq', 'gRNA_4665.fastq', 'gRNA_4704.fastq', 'gRNA_4734.fastq', 'gRNA_4735.fastq', 'gRNA_4770.fastq', 'gRNA_4782.fastq', 'gRNA_4783.fastq', 'gRNA_4826.fastq', 'gRNA_4827.fastq', 'gRNA_4828.fastq', 'gRNA_4829.fastq', 'gRNA_4858.fastq', 'gRNA_4884.fastq', 'gRNA_4885.fastq', 'gRNA_4888.fastq', 'gRNA_4889.fastq', 'gRNA_4893.fastq', 'gRNA_4894.fastq', 'gRNA_4961.fastq', 'gRNA_4969.fastq', 'gRNA_5176.fastq', 'gRNA_5194.fastq', 'gRNA_5227.fastq', 'gRNA_5228.fastq', 'gRNA_5229.fastq', 'gRNA_5236.fastq', 'gRNA_5237.fastq', 'gRNA_5319.fastq', 'gRNA_5372.fastq', 'gRNA_5373.fastq', 'gRNA_5374.fastq', 'gRNA_5454.fastq', 'gRNA_5455.fastq', 'gRNA_5456.fastq', 'gRNA_5477.fastq', 'gRNA_5501.fastq', 'gRNA_5509.fastq', 'gRNA_5561.fastq', 'gRNA_5614.fastq', 'gRNA_5615.fastq', 'gRNA_5618.fastq', 'gRNA_5620.fastq', 'gRNA_5621.fastq', 'gRNA_5623.fastq', 'gRNA_5624.fastq', 'gRNA_5625.fastq', 'gRNA_5626.fastq', 'gRNA_5627.fastq', 'gRNA_5628.fastq', 'gRNA_5740.fastq', 'gRNA_5741.fastq', 'gRNA_5742.fastq', 'gRNA_5769.fastq', 'gRNA_5772.fastq', 'gRNA_5773.fastq', 'gRNA_5776.fastq', 'gRNA_5777.fastq', 'gRNA_5792.fastq', 'gRNA_5854.fastq', 'gRNA_5860.fastq', 'gRNA_5861.fastq', 'gRNA_5864.fastq', 'gRNA_5865.fastq', 'gRNA_5912.fastq', 'gRNA_6000.fastq', 'gRNA_6063.fastq', 'gRNA_6064.fastq', 'gRNA_6080.fastq', 'gRNA_6081.fastq', 'gRNA_6086.fastq', 'gRNA_6087.fastq', 'gRNA_6103.fastq', 'gRNA_6104.fastq', 'gRNA_6105.fastq', 'gRNA_6109.fastq', 'gRNA_6110.fastq', 'gRNA_6111.fastq', 'gRNA_6112.fastq', 'gRNA_6113.fastq', 'gRNA_6117.fastq', 'gRNA_6125.fastq', 'gRNA_6134.fastq', 'gRNA_6135.fastq', 'gRNA_6257.fastq', 'gRNA_6265.fastq', 'gRNA_6266.fastq', 'gRNA_6383.fastq', 'gRNA_6384.fastq', 'gRNA_6472.fastq', 'gRNA_6473.fastq', 'gRNA_6479.fastq', 'gRNA_6480.fastq', 'gRNA_6487.fastq', 'gRNA_6488.fastq', 'gRNA_6525.fastq', 'gRNA_6526.fastq', 'gRNA_6527.fastq', 'gRNA_6604.fastq', 'gRNA_6629.fastq', 'gRNA_6712.fastq', 'gRNA_6717.fastq', 'gRNA_6743.fastq', 'gRNA_6744.fastq', 'gRNA_6745.fastq', 'gRNA_6759.fastq', 'gRNA_6781.fastq', 'gRNA_6782.fastq', 'gRNA_6797.fastq', 'gRNA_6829.fastq', 'gRNA_6830.fastq', 'gRNA_6831.fastq', 'gRNA_6832.fastq', 'gRNA_6833.fastq', 'gRNA_6834.fastq', 'gRNA_6835.fastq', 'gRNA_6837.fastq', 'gRNA_6841.fastq', 'gRNA_6842.fastq', 'gRNA_6848.fastq', 'gRNA_6849.fastq', 'gRNA_6888.fastq', 'gRNA_6889.fastq', 'gRNA_6890.fastq', 'gRNA_6894.fastq', 'gRNA_6895.fastq', 'gRNA_6912.fastq', 'gRNA_6913.fastq', 'gRNA_6914.fastq', 'gRNA_6915.fastq', 'gRNA_6992.fastq', 'gRNA_7029.fastq', 'gRNA_7143.fastq', 'gRNA_7144.fastq', 'gRNA_7148.fastq', 'gRNA_7150.fastq', 'gRNA_7152.fastq', 'gRNA_7170.fastq', 'gRNA_7171.fastq', 'gRNA_7188.fastq', 'gRNA_7203.fastq', 'gRNA_7204.fastq', 'gRNA_7205.fastq', 'gRNA_7214.fastq', 'gRNA_7264.fastq', 'gRNA_7308.fastq', 'gRNA_7309.fastq', 'gRNA_7310.fastq', 'gRNA_7384.fastq', 'gRNA_7392.fastq', 'gRNA_7393.fastq', 'gRNA_7428.fastq', 'gRNA_7429.fastq', 'gRNA_7430.fastq', 'gRNA_7467.fastq', 'gRNA_7468.fastq', 'gRNA_7473.fastq', 'gRNA_7478.fastq', 'gRNA_7479.fastq', 'gRNA_7481.fastq', 'gRNA_7482.fastq', 'gRNA_7509.fastq', 'gRNA_7510.fastq', 'gRNA_7511.fastq', 'gRNA_7512.fastq', 'gRNA_7513.fastq', 'gRNA_7514.fastq', 'gRNA_7557.fastq', 'gRNA_7558.fastq', 'gRNA_7602.fastq', 'gRNA_7627.fastq', 'gRNA_7664.fastq', 'gRNA_7667.fastq', 'gRNA_7683.fastq', 'gRNA_7684.fastq', 'gRNA_7765.fastq', 'gRNA_7787.fastq', 'gRNA_7812.fastq', 'gRNA_7813.fastq', 'gRNA_7814.fastq', 'gRNA_7815.fastq', 'gRNA_7816.fastq', 'gRNA_7822.fastq', 'gRNA_7823.fastq', 'gRNA_7826.fastq', 'gRNA_7827.fastq', 'gRNA_7828.fastq', 'gRNA_7829.fastq', 'gRNA_7839.fastq', 'gRNA_7843.fastq', 'gRNA_7873.fastq', 'gRNA_7885.fastq', 'gRNA_7886.fastq', 'gRNA_7901.fastq', 'gRNA_7902.fastq', 'gRNA_7917.fastq', 'gRNA_7918.fastq', 'gRNA_7919.fastq', 'gRNA_7935.fastq', 'gRNA_7956.fastq', 'gRNA_8028.fastq', 'gRNA_8198.fastq', 'gRNA_8216.fastq', 'gRNA_8217.fastq', 'gRNA_8225.fastq', 'gRNA_8226.fastq', 'gRNA_8227.fastq', 'gRNA_8228.fastq', 'gRNA_8241.fastq', 'gRNA_8302.fastq', 'gRNA_8366.fastq', 'gRNA_8367.fastq', 'gRNA_8409.fastq', 'gRNA_8410.fastq', 'gRNA_8493.fastq', 'gRNA_8494.fastq', 'gRNA_8513.fastq', 'gRNA_8569.fastq', 'gRNA_8650.fastq', 'gRNA_8651.fastq', 'gRNA_8652.fastq', 'gRNA_8668.fastq', 'gRNA_8672.fastq', 'gRNA_8673.fastq', 'gRNA_8695.fastq', 'gRNA_8696.fastq', 'gRNA_8699.fastq', 'gRNA_8775.fastq', 'gRNA_8782.fastq', 'gRNA_8783.fastq', 'gRNA_8784.fastq', 'gRNA_8789.fastq', 'gRNA_8790.fastq', 'gRNA_8791.fastq', 'gRNA_8793.fastq', 'gRNA_8794.fastq', 'gRNA_8795.fastq', 'gRNA_8803.fastq', 'gRNA_8804.fastq', 'gRNA_8808.fastq', 'gRNA_8813.fastq', 'gRNA_8814.fastq', 'gRNA_8824.fastq', 'gRNA_8825.fastq', 'gRNA_8826.fastq', 'gRNA_8827.fastq', 'gRNA_8831.fastq', 'gRNA_8833.fastq', 'gRNA_8834.fastq', 'gRNA_8835.fastq', 'gRNA_8840.fastq', 'gRNA_8841.fastq', 'gRNA_8852.fastq', 'gRNA_8854.fastq', 'gRNA_8855.fastq', 'gRNA_8857.fastq', 'gRNA_8858.fastq', 'gRNA_8861.fastq', 'gRNA_8862.fastq', 'gRNA_8867.fastq', 'gRNA_8868.fastq', 'gRNA_8869.fastq', 'gRNA_8891.fastq', 'gRNA_8893.fastq', 'gRNA_8895.fastq', 'gRNA_8896.fastq', 'gRNA_8897.fastq', 'gRNA_8935.fastq', 'gRNA_8936.fastq', 'gRNA_8997.fastq', 'gRNA_8998.fastq', 'gRNA_8999.fastq', 'gRNA_9000.fastq', 'gRNA_9037.fastq', 'gRNA_9041.fastq', 'gRNA_9055.fastq', 'gRNA_9056.fastq', 'gRNA_9063.fastq', 'gRNA_9064.fastq', 'gRNA_9084.fastq', 'gRNA_9085.fastq', 'gRNA_9105.fastq', 'gRNA_9114.fastq', 'gRNA_9115.fastq', 'gRNA_9116.fastq', 'gRNA_9286.fastq', 'gRNA_9392.fastq', 'gRNA_9410.fastq', 'gRNA_9411.fastq', 'gRNA_9513.fastq', 'gRNA_9611.fastq', 'gRNA_9612.fastq', 'gRNA_9624.fastq', 'gRNA_9625.fastq', 'gRNA_9703.fastq', 'gRNA_9705.fastq', 'gRNA_9706.fastq', 'gRNA_9730.fastq', 'gRNA_9744.fastq', 'gRNA_9745.fastq', 'gRNA_9838.fastq', 'gRNA_9875.fastq', 'gRNA_9876.fastq', 'gRNA_9881.fastq', 'gRNA_10049.fastq', 'gRNA_10106.fastq', 'gRNA_10107.fastq', 'gRNA_10117.fastq', 'gRNA_10118.fastq', 'gRNA_10150.fastq', 'gRNA_10274.fastq', 'gRNA_10275.fastq', 'gRNA_10306.fastq', 'gRNA_10307.fastq', 'gRNA_10336.fastq', 'gRNA_10337.fastq', 'gRNA_10342.fastq', 'gRNA_10343.fastq', 'gRNA_10363.fastq', 'gRNA_10378.fastq', 'gRNA_10379.fastq', 'gRNA_10380.fastq', 'gRNA_10397.fastq', 'gRNA_10406.fastq', 'gRNA_10436.fastq', 'gRNA_10437.fastq', 'gRNA_10447.fastq', 'gRNA_10448.fastq', 'gRNA_10456.fastq', 'gRNA_10466.fastq', 'gRNA_10467.fastq', 'gRNA_10468.fastq', 'gRNA_10504.fastq', 'gRNA_10546.fastq', 'gRNA_10547.fastq', 'gRNA_10548.fastq', 'gRNA_10571.fastq', 'gRNA_10572.fastq', 'gRNA_10573.fastq', 'gRNA_10574.fastq', 'gRNA_10595.fastq', 'gRNA_10596.fastq', 'gRNA_10597.fastq', 'gRNA_10598.fastq', 'gRNA_10617.fastq', 'gRNA_10618.fastq', 'gRNA_10622.fastq', 'gRNA_10623.fastq', 'gRNA_10632.fastq', 'gRNA_10633.fastq', 'gRNA_10634.fastq', 'gRNA_10635.fastq', 'gRNA_10636.fastq', 'gRNA_10637.fastq', 'gRNA_10656.fastq', 'gRNA_10657.fastq', 'gRNA_10664.fastq', 'gRNA_10665.fastq', 'gRNA_10679.fastq', 'gRNA_10680.fastq', 'gRNA_10681.fastq', 'gRNA_10684.fastq', 'gRNA_10690.fastq', 'gRNA_10770.fastq', 'gRNA_10909.fastq', 'gRNA_10910.fastq', 'gRNA_10929.fastq', 'gRNA_10930.fastq', 'gRNA_10932.fastq', 'gRNA_10955.fastq', 'gRNA_10969.fastq', 'gRNA_10970.fastq', 'gRNA_10971.fastq', 'gRNA_11017.fastq', 'gRNA_11018.fastq', 'gRNA_11069.fastq', 'gRNA_11070.fastq', 'gRNA_11071.fastq', 'gRNA_11098.fastq', 'gRNA_11099.fastq', 'gRNA_11111.fastq', 'gRNA_11112.fastq', 'gRNA_11113.fastq', 'gRNA_11114.fastq', 'gRNA_11122.fastq', 'gRNA_11132.fastq', 'gRNA_11133.fastq', 'gRNA_11136.fastq', 'gRNA_11141.fastq', 'gRNA_11142.fastq', 'gRNA_11143.fastq', 'gRNA_11144.fastq', 'gRNA_11157.fastq', 'gRNA_11158.fastq', 'gRNA_11159.fastq', 'gRNA_11169.fastq', 'gRNA_11182.fastq', 'gRNA_11195.fastq', 'gRNA_11208.fastq', 'gRNA_11209.fastq', 'gRNA_11218.fastq', 'gRNA_11219.fastq', 'gRNA_11223.fastq', 'gRNA_11224.fastq', 'gRNA_11284.fastq', 'gRNA_11285.fastq', 'gRNA_11298.fastq', 'gRNA_11305.fastq', 'gRNA_11306.fastq', 'gRNA_11312.fastq', 'gRNA_11315.fastq', 'gRNA_11319.fastq', 'gRNA_11322.fastq', 'gRNA_11323.fastq', 'gRNA_11324.fastq', 'gRNA_11325.fastq', 'gRNA_11326.fastq', 'gRNA_11336.fastq', 'gRNA_11337.fastq', 'gRNA_11449.fastq', 'gRNA_11450.fastq', 'gRNA_11454.fastq', 'gRNA_11499.fastq', 'gRNA_11500.fastq', 'gRNA_11532.fastq', 'gRNA_11533.fastq', 'gRNA_11581.fastq', 'gRNA_11582.fastq', 'gRNA_11589.fastq', 'gRNA_11590.fastq', 'gRNA_11607.fastq', 'gRNA_11608.fastq', 'gRNA_11609.fastq', 'gRNA_11670.fastq', 'gRNA_11671.fastq', 'gRNA_11689.fastq', 'gRNA_11701.fastq', 'gRNA_11702.fastq', 'gRNA_11703.fastq', 'gRNA_11748.fastq', 'gRNA_11796.fastq', 'gRNA_11797.fastq', 'gRNA_11798.fastq', 'gRNA_11967.fastq', 'gRNA_11968.fastq', 'gRNA_11992.fastq', 'gRNA_11993.fastq', 'gRNA_11994.fastq', 'gRNA_12001.fastq', 'gRNA_12002.fastq', 'gRNA_12006.fastq', 'gRNA_12007.fastq', 'gRNA_12024.fastq', 'gRNA_12025.fastq', 'gRNA_12026.fastq', 'gRNA_12062.fastq', 'gRNA_12063.fastq', 'gRNA_12064.fastq', 'gRNA_12065.fastq', 'gRNA_12079.fastq', 'gRNA_12080.fastq', 'gRNA_12081.fastq', 'gRNA_12151.fastq', 'gRNA_12164.fastq', 'gRNA_12197.fastq', 'gRNA_12203.fastq', 'gRNA_12243.fastq', 'gRNA_12244.fastq', 'gRNA_12270.fastq', 'gRNA_12271.fastq', 'gRNA_12272.fastq', 'gRNA_12369.fastq', 'gRNA_12370.fastq', 'gRNA_12383.fastq', 'gRNA_12386.fastq', 'gRNA_12394.fastq', 'gRNA_12403.fastq', 'gRNA_12483.fastq', 'gRNA_12498.fastq', 'gRNA_12499.fastq', 'gRNA_12500.fastq', 'gRNA_12501.fastq', 'gRNA_12502.fastq', 'gRNA_12508.fastq', 'gRNA_12509.fastq', 'gRNA_12510.fastq', 'gRNA_12521.fastq', 'gRNA_12522.fastq', 'gRNA_12523.fastq', 'gRNA_12528.fastq', 'gRNA_12529.fastq', 'gRNA_12530.fastq', 'gRNA_12534.fastq', 'gRNA_12535.fastq', 'gRNA_12536.fastq', 'gRNA_12537.fastq', 'gRNA_12538.fastq', 'gRNA_12547.fastq', 'gRNA_12548.fastq', 'gRNA_12549.fastq', 'gRNA_12556.fastq', 'gRNA_12557.fastq', 'gRNA_12558.fastq', 'gRNA_12560.fastq', 'gRNA_12561.fastq', 'gRNA_12562.fastq', 'gRNA_12567.fastq', 'gRNA_12576.fastq', 'gRNA_12577.fastq', 'gRNA_12578.fastq', 'gRNA_12579.fastq', 'gRNA_12580.fastq', 'gRNA_12581.fastq', 'gRNA_12582.fastq', 'gRNA_12583.fastq', 'gRNA_12584.fastq', 'gRNA_12585.fastq', 'gRNA_12586.fastq', 'gRNA_12587.fastq', 'gRNA_12588.fastq', 'gRNA_12589.fastq', 'gRNA_12590.fastq', 'gRNA_12591.fastq', 'gRNA_12592.fastq', 'gRNA_12595.fastq', 'gRNA_12596.fastq', 'gRNA_12597.fastq', 'gRNA_12598.fastq', 'gRNA_12599.fastq', 'gRNA_12600.fastq', 'gRNA_12601.fastq', 'gRNA_12602.fastq', 'gRNA_12604.fastq', 'gRNA_12606.fastq', 'gRNA_12607.fastq', 'gRNA_12608.fastq', 'gRNA_12609.fastq', 'gRNA_12610.fastq', 'gRNA_12618.fastq', 'gRNA_12624.fastq', 'gRNA_12625.fastq', 'gRNA_12635.fastq', 'gRNA_12652.fastq', 'gRNA_12653.fastq', 'gRNA_12654.fastq', 'gRNA_12655.fastq', 'gRNA_12754.fastq', 'gRNA_12779.fastq', 'gRNA_12826.fastq', 'gRNA_12831.fastq', 'gRNA_12832.fastq', 'gRNA_12844.fastq', 'gRNA_12845.fastq', 'gRNA_12850.fastq', 'gRNA_12890.fastq', 'gRNA_12891.fastq', 'gRNA_12894.fastq', 'gRNA_12922.fastq', 'gRNA_12923.fastq', 'gRNA_12925.fastq', 'gRNA_12930.fastq', 'gRNA_12954.fastq', 'gRNA_12989.fastq', 'gRNA_12990.fastq', 'gRNA_12991.fastq', 'gRNA_12999.fastq', 'gRNA_13002.fastq', 'gRNA_13003.fastq', 'gRNA_13004.fastq', 'gRNA_13005.fastq', 'gRNA_13006.fastq', 'gRNA_13007.fastq', 'gRNA_13008.fastq', 'gRNA_13009.fastq', 'gRNA_13010.fastq', 'gRNA_13011.fastq', 'gRNA_13058.fastq', 'gRNA_13059.fastq', 'gRNA_13260.fastq', 'gRNA_13261.fastq', 'gRNA_13262.fastq', 'gRNA_13263

In [10]:
# I think this is already repeated above so I have two different named files with the same thing
config_df
config_df.to_csv("config_file.txt", sep= " ", index=False)

# Example post-processing

In [3]:
def crispresso_compiler(samp, sample_id, fp):
    """ 
    Takes in list of sample names (see cell above)
    Returns compiled dictionary of dataframes containing editing information for each sensor
    - key for each is the sample_id name
    
    Includes:
    1. corr_perc = pure correct editing
    2. target_base_edit_perc = target base editing perc (including edits with bystander editing)
    3. wt_perc
    4. byproduct information (indels, substitutions, ambiguous)
    """

    df_edits = []
    for k in samp: 
        concated = pd.read_csv(f'{fp}/{k}_crispresso_aggregated.csv')
        concated = concated.fillna(0)

        #somehow wasn't able to find the initial set of code that I used for this...

        #go through all of the samples and do it step by step
        sample_ids = []
        #sample_num = []
        rii = []
        raaa = []
        r_lowqual = []
        ra_hdr = []
        ra_wt = []
        r_unaligned = []
        no_edit = []
        correct = []
        target_base_editing = []
        byproduct_all = []
        byproduct_indel = []
        byproduct_sub = []
        byproduct_ambig = []
        for i in np.unique(concated['Guide_ID']):
            sample_ids.append(i)

            subset = concated[concated['Guide_ID']==i]

            wt = subset[subset['Amplicon']=='Reference']
            edit = subset[subset['Amplicon']=='HDR']

            #sample_num.append(wt['sample_num'].values[0])
            rii1 = wt['Reads_in_input'].values[0]
            r1 = wt['Reads_aligned_all_amplicons'].values[0]
            rii.append(rii1)
            raaa.append(r1)
            r_lowqual.append(rii1-r1)

            r2 = edit['Reads_aligned'].values[0]
            r3 = wt['Reads_aligned'].values[0]
            ra_hdr.append(r2)
            ra_wt.append(r3)
            r_unaligned.append(r1 - (r2+r3))

            no_edit.append(wt['Unmodified'].values[0])
            correct.append(edit['Unmodified'].values[0])
            target_base_editing.append(edit['Modified'].values[0] + edit['Unmodified'].values[0])

            byprod_all = wt['Modified'].values[0] + edit['Modified'].values[0] + (r1 - (r2+r3)) #add unaligned reads
            sub_all = wt['Only Substitutions'].values[0] + edit['Only Substitutions'].values[0]
            indel_all = wt['Only Deletions'].values[0] + wt['Only Insertions'].values[0] + wt['Insertions and Deletions'].values[0] + edit['Only Deletions'].values[0] + edit['Only Insertions'].values[0] + edit['Insertions and Deletions'].values[0]
            ambig_all = byprod_all - sub_all - indel_all

            byproduct_all.append(byprod_all)
            byproduct_indel.append(indel_all)
            byproduct_sub.append(sub_all)
            byproduct_ambig.append(ambig_all)


        cols = ["Guide_ID", "Reads_in_input","Reads_lowqual", "Reads_aligned_all_amplicons","Reads_aligned_WT", "Reads_aligned_HDR", "Reads_unaligned", "WT","correct_edit", "target_base_edit", "byproduct_all","byproduct_INDEL","byproduct_sub","byproduct_ambiguous"]
        col_vals = [ sample_ids, rii, r_lowqual, raaa, ra_wt, ra_hdr, r_unaligned, no_edit, correct, target_base_editing, byproduct_all, byproduct_indel, byproduct_sub, byproduct_ambig]

        out = pd.DataFrame(dict(zip(cols, col_vals)))
        out['corr_perc'] = 100*(out['correct_edit']/out['Reads_aligned_all_amplicons'])
        out['target_base_edit_perc'] = 100*(out['target_base_edit']/out['Reads_aligned_all_amplicons'])
        out['WT_perc'] = 100*(out['WT']/out['Reads_aligned_all_amplicons'])
        out['byproduct_all_perc'] =  100*(out['byproduct_all']/out['Reads_aligned_all_amplicons'])
        out['byproduct_INDEL_perc'] =  100*(out['byproduct_INDEL']/out['Reads_aligned_all_amplicons'])
        out['byproduct_sub_perc'] =  100*(out['byproduct_sub']/out['Reads_aligned_all_amplicons'])
        out['byproduct_ambiguous_perc'] =100*(out['byproduct_ambiguous']/out['Reads_aligned_all_amplicons'])
        out = out.fillna(0)

        df_edits.append(out)

    edit_dict = dict(zip(sample_id, df_edits))

    return edit_dict

In [4]:
config = pd.read_csv('/net/bmc-lab2/data/lab/sanchezrivera/hcevasco/DASIT/251212San/sensor_extraction_fastq_split_config_HC_DASIT.txt', sep=' ')
list(config['folder_name'])

['D25-251027_guide_split_BARCODES',
 'D25-251028_guide_split_BARCODES',
 'D25-251029_guide_split_BARCODES',
 'D25-251030_guide_split_BARCODES',
 'D25-251031_guide_split_BARCODES',
 'D25-251032_guide_split_BARCODES',
 'D25-251033_guide_split_BARCODES',
 'D25-251034_guide_split_BARCODES',
 'D25-251035_guide_split_BARCODES',
 'D25-251036_guide_split_BARCODES',
 'D25-251037_guide_split_BARCODES',
 'D25-251038_guide_split_BARCODES',
 'D25-251039_guide_split_BARCODES',
 'D25-251040_guide_split_BARCODES',
 'D25-251041_guide_split_BARCODES',
 'D25-251042_guide_split_BARCODES',
 'D25-251043_guide_split_BARCODES']

In [5]:
#example_inputs
samp = ['D25-251027_guide_split_BARCODES',
 'D25-251028_guide_split_BARCODES',
 'D25-251029_guide_split_BARCODES',
 'D25-251030_guide_split_BARCODES',
 'D25-251031_guide_split_BARCODES',
 'D25-251032_guide_split_BARCODES',
 'D25-251033_guide_split_BARCODES',
 'D25-251034_guide_split_BARCODES',
 'D25-251035_guide_split_BARCODES',
 'D25-251036_guide_split_BARCODES',
 'D25-251037_guide_split_BARCODES',
 'D25-251038_guide_split_BARCODES',
 'D25-251039_guide_split_BARCODES',
 'D25-251040_guide_split_BARCODES',
 'D25-251041_guide_split_BARCODES',
 'D25-251042_guide_split_BARCODES',
 'D25-251043_guide_split_BARCODES']

sample_id = ["D0_preEPO_rep1",
    "D0_preEPO_rep2",
    "D0_preEPO_rep3",
    "D3_rep2",
    "D3_rep3",
    "D5_noPuro_rep1",
    "D5_noPuro_rep2",
    "D5_noPuro_rep3",
    "D5_puro_rep1",
    "D5_puro_rep2",
    "D5_puro_rep3",
    "D15_noPuro_rep1",
    "D15_noPuro_rep2",
    "D15_noPuro_rep3",
    "D15_puro_rep1",
    "D15_puro_rep2",
    "D15_puro_rep3",]

#filepath for crispresso data
fp = '/net/bmc-lab2/data/lab/sanchezrivera/hcevasco/DASIT/251212San/crispresso'

edit_dict = crispresso_compiler(samp, sample_id, fp)

In [15]:
#can then access editing through 
edit_dict['D5_noPuro_rep3']

,Guide_ID,Reads_in_input,Reads_lowqual,Reads_aligned_all_amplicons,Reads_aligned_WT,Reads_aligned_HDR,Reads_unaligned,WT,correct_edit,target_base_edit,...,byproduct_INDEL,byproduct_sub,byproduct_ambiguous,corr_perc,target_base_edit_perc,WT_perc,byproduct_all_perc,byproduct_INDEL_perc,byproduct_sub_perc,byproduct_ambiguous_perc
0,gRNA_1,1507,0,1507,1473,34,0,1312,13,34,...,0,182,0,0.862641,2.256138,87.060385,12.076974,0.000000,12.076974,0.000000
1,gRNA_1000,7056,3,7053,4587,2460,6,345,49,2460,...,3,6649,7,0.694740,34.878775,4.891536,94.413725,0.042535,94.271941,0.099249
2,gRNA_10049,10656,0,10656,3090,7381,185,311,232,7381,...,43,9878,192,2.177177,69.266141,2.918544,94.904279,0.403529,92.698949,1.801802
3,gRNA_1008,15290,66,15224,3086,12123,15,2188,8974,12123,...,78,3918,66,58.946400,79.630846,14.372044,26.681555,0.512349,25.735681,0.433526
4,gRNA_1009,10451,25,10426,1213,9204,9,627,6821,9204,...,56,2870,52,65.422981,88.279302,6.013812,28.563207,0.537119,27.527336,0.498753
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1065,gRNA_9876,2628,0,2628,395,2222,11,369,1879,2222,...,9,360,11,71.499239,84.550989,14.041096,14.459665,0.342466,13.698630,0.418569
1066,gRNA_9881,344,0,344,334,10,0,99,0,10,...,0,245,0,0.000000,2.906977,28.779070,71.220930,0.000000,71.220930,0.000000
1067,gRNA_992,4480,0,4480,4110,368,2,3632,352,368,...,3,474,19,7.857143,8.214286,81.071429,11.071429,0.066964,10.580357,0.424107
1068,gRNA_993,3535,51,3484,2141,1340,3,1731,1259,1340,...,50,396,48,36.136625,38.461538,49.684271,14.179104,1.435132,11.366246,1.377727
1069,gRNA_999,17392,30,17362,12604,4737,21,1847,31,4737,...,41,15408,35,0.178551,27.283723,10.638175,89.183274,0.236148,88.745536,0.201590

# Merging sensor editing results

It's often useful to merge sensor editing results from the same time-point to make a maximum likelihood estimate of sensor editing:

In [16]:
def MLE_merge(edit_dict, samps_to_merge, new_name):
    """ 
    combine replicates to generate best estimate of sensor editing
    only works for combinations of 3 replicates (could be modified)
    """
    cols_to_add = ['Reads_in_input', 'Reads_lowqual',
       'Reads_aligned_all_amplicons', 'Reads_aligned_WT', 'Reads_aligned_HDR',
       'Reads_unaligned', 'WT', 'correct_edit', 'target_base_edit',
       'byproduct_all', 'byproduct_INDEL', 'byproduct_sub',
       'byproduct_ambiguous',]
    
    comb_holder = []
    for k in samps_to_merge:
        a = edit_dict[k[0]]
        b = edit_dict[k[1]]
        c = edit_dict[k[2]]

        #check that guide indeces match
        assert list(a['Guide_ID'])==list(b['Guide_ID'])==list(c['Guide_ID']), 'indexes dont match'

        a2 = a[cols_to_add]
        b2 = b[cols_to_add]
        c2 = c[cols_to_add]

        comb = a2+b2+c2

        comb['Guide_ID'] = a['Guide_ID']

        #and reorganize columns
        col_order = ['Guide_ID'] + cols_to_add
        out = comb[col_order]

        #and then calcualte percentages
        out['corr_perc'] = 100*(out['correct_edit']/out['Reads_aligned_all_amplicons'])
        out['target_base_edit_perc'] = 100*(out['target_base_edit']/out['Reads_aligned_all_amplicons'])
        out['WT_perc'] = 100*(out['WT']/out['Reads_aligned_all_amplicons'])
        out['byproduct_all_perc'] =  100*(out['byproduct_all']/out['Reads_aligned_all_amplicons'])
        out['byproduct_INDEL_perc'] =  100*(out['byproduct_INDEL']/out['Reads_aligned_all_amplicons'])
        out['byproduct_sub_perc'] =  100*(out['byproduct_sub']/out['Reads_aligned_all_amplicons'])
        out['byproduct_ambiguous_perc'] =100*(out['byproduct_ambiguous']/out['Reads_aligned_all_amplicons'])
        out = out.fillna(0)

        comb_holder.append(out)

    out_dict = dict(zip(new_name, comb_holder))

    return out_dict

In [17]:
#e.g. if sample1, sample2, and sample3 were 
# from the same time-point and you wanted to merge them
'''["D0_preEPO_rep1",
    "D0_preEPO_rep2",
    "D0_preEPO_rep3",
    "D3_rep2",
    "D3_rep3",
    "D5_noPuro_rep1",
    "D5_noPuro_rep2",
    "D5_noPuro_rep3",
    "D5_puro_rep1",
    "D5_puro_rep2",
    "D5_puro_rep3",
    "D15_noPuro_rep1",
    "D15_noPuro_rep2",
    "D15_noPuro_rep3",
    "D15_puro_rep1",
    "D15_puro_rep2",
    "D15_puro_rep3",]
    '''
samps_to_merge = [["D0_preEPO_rep1", "D0_preEPO_rep2","D0_preEPO_rep3"], 
                  ["D5_noPuro_rep1", "D5_noPuro_rep2","D5_noPuro_rep3"],
                  ["D5_puro_rep1","D5_puro_rep2","D5_puro_rep3"],
                  ["D15_noPuro_rep1","D15_noPuro_rep2","D15_noPuro_rep3"],
                  ["D15_puro_rep1","D15_puro_rep2","D15_puro_rep3"]]
new_name = ['D0_preEPO_MLE', 'D5_noPuro_MLE', 'D5_puro_MLE', 'D15_noPuro_MLE', 'D15_puro_MLE']

comb_dict = MLE_merge(edit_dict, samps_to_merge, new_name)

/tmp/ipykernel_23591/3541396037.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  out['corr_perc'] = 100*(out['correct_edit']/out['Reads_aligned_all_amplicons'])
/tmp/ipykernel_23591/3541396037.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  out['target_base_edit_perc'] = 100*(out['target_base_edit']/out['Reads_aligned_all_amplicons'])
/tmp/ipykernel_23591/3541396037.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  out['WT_perc'] = 100*(out['WT']/out['Reads_aligned_all_amplicons'])
/tmp/ipykernel_23591/3541396037.py:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  out['byproduct_all_perc'] =  100*(out['byproduct_all']/out['Reads_aligned_all_amplicons'])
/tmp/ipykernel_23591/3541396037.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  out['byproduct_INDEL_perc'] =  100*(out['byproduct_INDEL']/out['Reads_aligned_all_amplicons'])
/tmp/ipykernel_23591/3541396037.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  out['byproduct_sub_perc'] =  100*(out['byproduct_sub']/out['Reads_aligned_all_amplicons'])
/tmp/ipykernel_23591/3541396037.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  out['byproduct_ambiguous_perc'] =100*(out['byproduct_ambiguous']/out['Reads_aligned_all_amplicons'])
/tmp/ipykernel_23591/3541396037.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  out['corr_perc'] = 100*(out['correct_edit']/out['Reads_aligned_all_amplicons'])
/tmp/ipykernel_23591/3541396037.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  out['target_base_edit_perc'] = 100*(out['target_base_edit']/out['Reads_aligned_all_amplicons'])
/tmp/ipykernel_23591/3541396037.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  out['WT_perc'] = 100*(out['WT']/out['Reads_aligned_all_amplicons'])
/tmp/ipykernel_23591/3541396037.py:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  out['byproduct_all_perc'] =  100*(out['byproduct_all']/out['Reads_aligned_all_amplicons'])
/tmp/ipykernel_23591/3541396037.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  out['byproduct_INDEL_perc'] =  100*(out['byproduct_INDEL']/out['Reads_aligned_all_amplicons'])
/tmp/ipykernel_23591/3541396037.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  out['byproduct_sub_perc'] =  100*(out['byproduct_sub']/out['Reads_aligned_all_amplicons'])
/tmp/ipykernel_23591/3541396037.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  out['byproduct_ambiguous_perc'] =100*(out['byproduct_ambiguous']/out['Reads_aligned_all_amplicons'])
/tmp/ipykernel_23591/3541396037.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  out['corr_perc'] = 100*(out['correct_edit']/out['Reads_aligned_all_amplicons'])
/tmp/ipykernel_23591/3541396037.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  out['target_base_edit_perc'] = 100*(out['target_base_edit']/out['Reads_aligned_all_amplicons'])
/tmp/ipykernel_23591/3541396037.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  out['WT_perc'] = 100*(out['WT']/out['Reads_aligned_all_amplicons'])
/tmp/ipykernel_23591/3541396037.py:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  out['byproduct_all_perc'] =  100*(out['byproduct_all']/out['Reads_aligned_all_amplicons'])
/tmp/ipykernel_23591/3541396037.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  out['byproduct_INDEL_perc'] =  100*(out['byproduct_INDEL']/out['Reads_aligned_all_amplicons'])
/tmp/ipykernel_23591/3541396037.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  out['byproduct_sub_perc'] =  100*(out['byproduct_sub']/out['Reads_aligned_all_amplicons'])
/tmp/ipykernel_23591/3541396037.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  out['byproduct_ambiguous_perc'] =100*(out['byproduct_ambiguous']/out['Reads_aligned_all_amplicons'])
/tmp/ipykernel_23591/3541396037.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  out['corr_perc'] = 100*(out['correct_edit']/out['Reads_aligned_all_amplicons'])
/tmp/ipykernel_23591/3541396037.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  out['target_base_edit_perc'] = 100*(out['target_base_edit']/out['Reads_aligned_all_amplicons'])
/tmp/ipykernel_23591/3541396037.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  out['WT_perc'] = 100*(out['WT']/out['Reads_aligned_all_amplicons'])
/tmp/ipykernel_23591/3541396037.py:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  out['byproduct_all_perc'] =  100*(out['byproduct_all']/out['Reads_aligned_all_amplicons'])
/tmp/ipykernel_23591/3541396037.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  out['byproduct_INDEL_perc'] =  100*(out['byproduct_INDEL']/out['Reads_aligned_all_amplicons'])
/tmp/ipykernel_23591/3541396037.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  out['byproduct_sub_perc'] =  100*(out['byproduct_sub']/out['Reads_aligned_all_amplicons'])
/tmp/ipykernel_23591/3541396037.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  out['byproduct_ambiguous_perc'] =100*(out['byproduct_ambiguous']/out['Reads_aligned_all_amplicons'])
/tmp/ipykernel_23591/3541396037.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  out['corr_perc'] = 100*(out['correct_edit']/out['Reads_aligned_all_amplicons'])
/tmp/ipykernel_23591/3541396037.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  out['target_base_edit_perc'] = 100*(out['target_base_edit']/out['Reads_aligned_all_amplicons'])
/tmp/ipykernel_23591/3541396037.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  out['WT_perc'] = 100*(out['WT']/out['Reads_aligned_all_amplicons'])
/tmp/ipykernel_23591/3541396037.py:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  out['byproduct_all_perc'] =  100*(out['byproduct_all']/out['Reads_aligned_all_amplicons'])
/tmp/ipykernel_23591/3541396037.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  out['byproduct_INDEL_perc'] =  100*(out['byproduct_INDEL']/out['Reads_aligned_all_amplicons'])
/tmp/ipykernel_23591/3541396037.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  out['byproduct_sub_perc'] =  100*(out['byproduct_sub']/out['Reads_aligned_all_amplicons'])
/tmp/ipykernel_23591/3541396037.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  out['byproduct_ambiguous_perc'] =100*(out['byproduct_ambiguous']/out['Reads_aligned_all_amplicons'])

In [18]:
#and accessing it
comb_dict['D0_preEPO_MLE']
#can then save to csv
comb_dict['D0_preEPO_MLE'].to_csv('/net/bmc-lab2/data/lab/sanchezrivera/hcevasco/DASIT/251212San/D0_preEPO_MLE.csv', sep='\t', index=False)
comb_dict['D5_noPuro_MLE'].to_csv('/net/bmc-lab2/data/lab/sanchezrivera/hcevasco/DASIT/251212San/D5_noPuro_MLE.csv', sep='\t', index=False)
comb_dict['D5_puro_MLE'].to_csv('/net/bmc-lab2/data/lab/sanchezrivera/hcevasco/DASIT/251212San/D5_puro_MLE.csv', sep='\t', index=False)
comb_dict['D15_noPuro_MLE'].to_csv('/net/bmc-lab2/data/lab/sanchezrivera/hcevasco/DASIT/251212San/D15_noPuro_MLE.csv', sep='\t', index=False)
comb_dict['D15_puro_MLE'].to_csv('/net/bmc-lab2/data/lab/sanchezrivera/hcevasco/DASIT/251212San/D15_puro_MLE.csv', sep='\t', index=False)

# !!! Move to the empirical_FDR_LFC.ipynb file from here to generate counts files and split them by condition

# MAGeCK example - I do this in the empirical_FDR_LFC.ipynb file

Example of taking the counts files and making them useable for MAGeCK. We want a table that has columns of samples and rows of guide counts.

In [21]:
config_df = pd.read_csv('/net/bmc-lab2/data/lab/sanchezrivera/hcevasco/DASIT/251212San/sensor_extraction_fastq_split_config_HC_DASIT.txt', sep=' ')


sample_id = ["D0_preEPO_rep1",
    "D0_preEPO_rep2",
    "D0_preEPO_rep3",
    "D3_rep2",
    "D3_rep3",
    "D5_noPuro_rep1",
    "D5_noPuro_rep2",
    "D5_noPuro_rep3",
    "D5_puro_rep1",
    "D5_puro_rep2",
    "D5_puro_rep3",
    "D15_noPuro_rep1",
    "D15_noPuro_rep2",
    "D15_noPuro_rep3",
    "D15_puro_rep1",
    "D15_puro_rep2",
    "D15_puro_rep3"]

samp = [i for i in config_df['folder_name']]

samp_dict = dict(zip(samp, sample_id))
samp_dict

{'D25-251027_guide_split_BARCODES': 'D0_preEPO_rep1',
 'D25-251028_guide_split_BARCODES': 'D0_preEPO_rep2',
 'D25-251029_guide_split_BARCODES': 'D0_preEPO_rep3',
 'D25-251030_guide_split_BARCODES': 'D3_rep2',
 'D25-251031_guide_split_BARCODES': 'D3_rep3',
 'D25-251032_guide_split_BARCODES': 'D5_noPuro_rep1',
 'D25-251033_guide_split_BARCODES': 'D5_noPuro_rep2',
 'D25-251034_guide_split_BARCODES': 'D5_noPuro_rep3',
 'D25-251035_guide_split_BARCODES': 'D5_puro_rep1',
 'D25-251036_guide_split_BARCODES': 'D5_puro_rep2',
 'D25-251037_guide_split_BARCODES': 'D5_puro_rep3',
 'D25-251038_guide_split_BARCODES': 'D15_noPuro_rep1',
 'D25-251039_guide_split_BARCODES': 'D15_noPuro_rep2',
 'D25-251040_guide_split_BARCODES': 'D15_noPuro_rep3',
 'D25-251041_guide_split_BARCODES': 'D15_puro_rep1',
 'D25-251042_guide_split_BARCODES': 'D15_puro_rep2',
 'D25-251043_guide_split_BARCODES': 'D15_puro_rep3'}

In [37]:
#-------UPDATE THESE 2 PARAMTERS----
fp = '/net/bmc-lab2/data/lab/sanchezrivera/hcevasco/DASIT/251212San/counts'
chosen_count_column = 'bc_count' #can also choose "matched_guide_count" or "total_guide_count"

df_holder = []
s_name = []
for i, k in enumerate(samp):
    aa = pd.read_csv(f'{fp}/{k}_count_df.csv')
    aa = aa[['Guide_ID', chosen_count_column]]

    s = samp_dict[k]

    aa = aa.rename(columns = {chosen_count_column:f'{s}'})

    if i>0:
        aa = aa.rename(columns = {'Guide_ID':'Guide_ID_x'})
    df_holder.append(aa)

join_out = pd.concat(df_holder, axis=1)
join_out = join_out[['Guide_ID'] + sample_id]
join_out

,Guide_ID,D0_preEPO_rep1,D0_preEPO_rep2,D0_preEPO_rep3,D3_rep2,D3_rep3,D5_noPuro_rep1,D5_noPuro_rep2,D5_noPuro_rep3,D5_puro_rep1,D5_puro_rep2,D5_puro_rep3,D15_noPuro_rep1,D15_noPuro_rep2,D15_noPuro_rep3,D15_puro_rep1,D15_puro_rep2,D15_puro_rep3
0,gRNA_1,3271.0,4002.0,3449.0,3063.0,5311.0,4440.0,4417.0,2419.0,3444.0,4838.0,2579.0,4986.0,3397.0,3280.0,2378.0,2295.0,2903.0
1,gRNA_2,963.0,1241.0,879.0,2536.0,3586.0,2709.0,2791.0,1449.0,2670.0,4262.0,1894.0,1769.0,1308.0,1100.0,1352.0,557.0,655.0
2,gRNA_3,1914.0,2102.0,1828.0,3187.0,4283.0,3402.0,3432.0,1929.0,2658.0,4051.0,2089.0,3899.0,2042.0,2291.0,1982.0,1713.0,1880.0
3,gRNA_67,2147.0,1938.0,2189.0,3674.0,2576.0,2443.0,2343.0,1557.0,2115.0,3380.0,2362.0,1357.0,909.0,841.0,655.0,639.0,548.0
4,gRNA_84,28663.0,27697.0,7336.0,23349.0,22093.0,13262.0,21993.0,11535.0,13180.0,16743.0,12417.0,21964.0,12916.0,13077.0,8989.0,9483.0,12326.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1065,gRNA_13604,30467.0,30615.0,18579.0,18333.0,19719.0,14913.0,22348.0,10267.0,13505.0,19231.0,14054.0,30553.0,13120.0,14259.0,11951.0,11315.0,14722.0
1066,gRNA_13605,12679.0,13332.0,7547.0,5166.0,8568.0,4087.0,7456.0,5165.0,5329.0,8375.0,6138.0,13771.0,4087.0,5664.0,4227.0,3517.0,5259.0
1067,gRNA_13606,50781.0,53566.0,24407.0,19358.0,19493.0,14310.0,29767.0,16994.0,17364.0,28438.0,28339.0,41648.0,22720.0,23874.0,16749.0,23209.0,23078.0
1068,gRNA_13607,26689.0,26676.0,13389.0,11723.0,11537.0,7951.0,13292.0,8560.0,9589.0,13902.0,6733.0,17044.0,9112.0,11379.0,8432.0,8798.0,11886.0
1069,gRNA_13608,5656.0,5616.0,2778.0,3386.0,2626.0,1933.0,3212.0,2132.0,2629.0,4269.0,2105.0,4170.0,2989.0,3795.0,3099.0,2531.0,3529.0

In [44]:
#and then add in the gene information as well
df = pd.read_csv('/net/bmc-lab2/data/lab/sanchezrivera/hcevasco/DASIT/251212San/MBESv2_ABE_only.csv')
guide_gene = dict(zip(df['gRNA_id'], df['gene_name_h']))
print(guide_gene)
#changed to gene_name_h to match the updated csv with gene names instead of Hugo_Symbol
genes = []
for i, val in join_out.iterrows():

    k = val['Guide_ID']
    gene = guide_gene[k]

    #make all the neutral guides have the same name
    # ABE library has safe and nt guides so and they don't have any gene names in the column 
    # so they show up as NaN
    if pd.isna(gene):
        gene = 'controlsgRNA'
    genes.append(gene)

join_out['gene'] = genes
join_out = join_out.rename(columns = {'Guide_ID':'sgRNA'})
join_out = join_out[['sgRNA', 'gene'] + sample_id]
join_out

#the first 2 column names need to be 'sgRNA' and 'gene'

{'gRNA_1': 'ABL1', 'gRNA_2': 'ABL1', 'gRNA_3': 'ABL1', 'gRNA_67': 'AGO2', 'gRNA_84': 'AKT1', 'gRNA_85': 'AKT1', 'gRNA_95': 'AKT1', 'gRNA_120': 'AKT3', 'gRNA_121': 'AKT3', 'gRNA_122': 'AKT3', 'gRNA_196': 'ALK', 'gRNA_197': 'ALK', 'gRNA_198': 'ALK', 'gRNA_235': 'AMER1', 'gRNA_283': 'ANKRD11', 'gRNA_284': 'ANKRD11', 'gRNA_285': 'ANKRD11', 'gRNA_292': 'APC', 'gRNA_293': 'APC', 'gRNA_299': 'APC', 'gRNA_300': 'APC', 'gRNA_497': 'ARAF', 'gRNA_498': 'ARAF', 'gRNA_528': 'ARID1A', 'gRNA_594': 'ARID1A', 'gRNA_671': 'ARID1A', 'gRNA_736': 'ARID1B', 'gRNA_740': 'ARID1B', 'gRNA_741': 'ARID1B', 'gRNA_767': 'ARID1B', 'gRNA_768': 'ARID1B', 'gRNA_769': 'ARID1B', 'gRNA_806': 'ARID1B', 'gRNA_807': 'ARID1B', 'gRNA_828': 'ARID2', 'gRNA_829': 'ARID2', 'gRNA_830': 'ARID2', 'gRNA_831': 'ARID2', 'gRNA_871': 'ARID2', 'gRNA_895': 'ARID5B', 'gRNA_896': 'ARID5B', 'gRNA_901': 'ARID5B', 'gRNA_974': 'ASXL2', 'gRNA_978': 'ASXL2', 'gRNA_979': 'ASXL2', 'gRNA_992': 'ATM', 'gRNA_993': 'ATM', 'gRNA_999': 'ATM', 'gRNA_1000': 'ATM', 'gRNA_1008': 'ATM', 'gRNA_1009': 'ATM', 'gRNA_1010': 'ATM', 'gRNA_1011': 'ATM', 'gRNA_1014': 'ATM', 'gRNA_1017': 'ATM', 'gRNA_1018': 'ATM', 'gRNA_1035': 'ATM', 'gRNA_1036': 'ATM', 'gRNA_1045': 'ATM', 'gRNA_1046': 'ATM', 'gRNA_1047': 'ATM', 'gRNA_1048': 'ATM', 'gRNA_1049': 'ATM', 'gRNA_1056': 'ATM', 'gRNA_1065': 'ATM', 'gRNA_1066': 'ATM', 'gRNA_1069': 'ATP6V1B2', 'gRNA_1082': 'ATR', 'gRNA_1083': 'ATR', 'gRNA_1095': 'ATR', 'gRNA_1109': 'ATR', 'gRNA_1121': 'ATRX', 'gRNA_1122': 'ATRX', 'gRNA_1127': 'ATRX', 'gRNA_1145': 'ATRX', 'gRNA_1146': 'ATRX', 'gRNA_1148': 'ATRX', 'gRNA_1149': 'ATRX', 'gRNA_1150': 'ATRX', 'gRNA_1151': 'ATRX', 'gRNA_1281': 'B2M', 'gRNA_1282': 'B2M', 'gRNA_1283': 'B2M', 'gRNA_1284': 'B2M', 'gRNA_1285': 'B2M', 'gRNA_1313': 'BAP1', 'gRNA_1314': 'BAP1', 'gRNA_1317': 'BAP1', 'gRNA_1318': 'BAP1', 'gRNA_1321': 'BAP1', 'gRNA_1322': 'BAP1', 'gRNA_1337': 'BAP1', 'gRNA_1338': 'BAP1', 'gRNA_1339': 'BAP1', 'gRNA_1340': 'BAP1', 'gRNA_1341': 'BAP1', 'gRNA_1342': 'BAP1', 'gRNA_1343': 'BAP1', 'gRNA_1361': 'BAP1', 'gRNA_1362': 'BAP1', 'gRNA_1373': 'BCL2', 'gRNA_1374': 'BCL2', 'gRNA_1375': 'BCL2', 'gRNA_1376': 'BCL2', 'gRNA_1377': 'BCL2', 'gRNA_1378': 'BCL2', 'gRNA_1379': 'BCL2', 'gRNA_1380': 'BCL2', 'gRNA_1381': 'BCL2', 'gRNA_1382': 'BCL2', 'gRNA_1383': 'BCL2', 'gRNA_1384': 'BCL2', 'gRNA_1385': 'BCL2', 'gRNA_1406': 'BCL2', 'gRNA_1407': 'BCL2', 'gRNA_1459': 'BCOR', 'gRNA_1460': 'BCOR', 'gRNA_1461': 'BCOR', 'gRNA_1463': 'BCOR', 'gRNA_1491': 'BCOR', 'gRNA_1492': 'BCOR', 'gRNA_1545': 'BRAF', 'gRNA_1548': 'BRAF', 'gRNA_1549': 'BRAF', 'gRNA_1550': 'BRAF', 'gRNA_1551': 'BRAF', 'gRNA_1552': 'BRAF', 'gRNA_1558': 'BRAF', 'gRNA_1559': 'BRAF', 'gRNA_1569': 'BRAF', 'gRNA_1570': 'BRAF', 'gRNA_1573': 'BRAF', 'gRNA_1583': 'BRCA1', 'gRNA_1588': 'BRCA2', 'gRNA_1590': 'BRCA2', 'gRNA_1591': 'BRCA2', 'gRNA_1592': 'BRCA2', 'gRNA_1696': 'BTK', 'gRNA_1725': 'CARD11', 'gRNA_1726': 'CARD11', 'gRNA_1733': 'CARD11', 'gRNA_1738': 'CARD11', 'gRNA_1817': 'CARD11', 'gRNA_1848': 'CARM1', 'gRNA_1855': 'CASP8', 'gRNA_1857': 'CASP8', 'gRNA_1858': 'CASP8', 'gRNA_1871': 'CBFB', 'gRNA_1875': 'CBFB', 'gRNA_1876': 'CBFB', 'gRNA_1882': 'CBL', 'gRNA_1898': 'CBL', 'gRNA_1901': 'CBL', 'gRNA_1904': 'CBL', 'gRNA_1905': 'CBL', 'gRNA_1906': 'CBL', 'gRNA_1925': 'CCND1', 'gRNA_1928': 'CCND1', 'gRNA_1929': 'CCND1', 'gRNA_1930': 'CCND1', 'gRNA_1953': 'CCND3', 'gRNA_1961': 'CCND3', 'gRNA_1962': 'CCND3', 'gRNA_1963': 'CCND3', 'gRNA_1972': 'CD79A', 'gRNA_1973': 'CD79A', 'gRNA_1977': 'CD79A', 'gRNA_1978': 'CD79A', 'gRNA_1980': 'CD79B', 'gRNA_1981': 'CD79B', 'gRNA_1983': 'CD79B', 'gRNA_1984': 'CD79B', 'gRNA_1985': 'CD79B', 'gRNA_1989': 'CDC73', 'gRNA_1994': 'CDC73', 'gRNA_1995': 'CDC73', 'gRNA_1996': 'CDC73', 'gRNA_2011': 'CDH1', 'gRNA_2012': 'CDH1', 'gRNA_2043': 'CDK12', 'gRNA_2044': 'CDK12', 'gRNA_2105': 'CDK8', 'gRNA_2133': 'CHEK2', 'gRNA_2134': 'CHEK2', 'gRNA_2135': 'CHEK2', 'gRNA_2154': 'CIC', 'gRNA_2202': 'CIC', 'gRNA_2203': 'CIC', 'gRNA_2215': 'CREBBP', 'gRNA_2234': 'CREBBP', 'gRNA_2240': 'CREBBP', 'gRNA_2265': 'CREBBP', 'gRNA_2268': 'CREBBP', 'gRNA_2269': 'CREBBP', 'gRNA_2270': 'CREBBP', 'gRNA_2281': 'CREBBP', 'gRNA_2284': 'CREBBP', 'gRNA_2285': 'CREBBP', 'gRNA_2292': 'CREBBP', 'gRNA_2293': 'CREBBP', 'gRNA_2294': 'CREBBP', 'gRNA_2297': 'CREBBP', 'gRNA_2298': 'CREBBP', 'gRNA_2316': 'CREBBP', 'gRNA_2326': 'CREBBP', 'gRNA_2384': 'CSF3R', 'gRNA_2385': 'CSF3R', 'gRNA_2386': 'CSF3R', 'gRNA_2387': 'CSF3R', 'gRNA_2388': 'CSF3R', 'gRNA_2398': 'CTCF', 'gRNA_2399': 'CTCF', 'gRNA_2401': 'CTCF', 'gRNA_2415': 'CTCF', 'gRNA_2416': 'CTCF', 'gRNA_2417': 'CTCF', 'gRNA_2440': 'CTCF', 'gRNA_2441': 'CTCF', 'gRNA_2445': 'CTNNB1', 'gRNA_2446': 'CTNNB1', 'gRNA_2457': 'CTNNB1', 'gRNA_2458': 'CTNNB1', 'gRNA_2466': 'CTNNB1', 'gRNA_2472': 'CTNNB1', 'gRNA_2473': 'CTNNB1', 'gRNA_2474': 'CTNNB1', 'gRNA_2494': 'CTNNB1', 'gRNA_2521': 'CUL3', 'gRNA_2526': 'CUL3', 'gRNA_2527': 'CUL3', 'gRNA_2568': 'DAXX', 'gRNA_2569': 'DAXX', 'gRNA_2620': 'DICER1', 'gRNA_2645': 'DIS3', 'gRNA_2648': 'DIS3', 'gRNA_2649': 'DIS3', 'gRNA_2657': 'DIS3', 'gRNA_2658': 'DIS3', 'gRNA_2671': 'DNMT1', 'gRNA_2679': 'DNMT3A', 'gRNA_2683': 'DNMT3A', 'gRNA_2684': 'DNMT3A', 'gRNA_2691': 'DNMT3A', 'gRNA_2692': 'DNMT3A', 'gRNA_2693': 'DNMT3A', 'gRNA_2694': 'DNMT3A', 'gRNA_2696': 'DNMT3A', 'gRNA_2697': 'DNMT3A', 'gRNA_2698': 'DNMT3A', 'gRNA_2702': 'DNMT3A', 'gRNA_2703': 'DNMT3A', 'gRNA_2723': 'DNMT3A', 'gRNA_2724': 'DNMT3A', 'gRNA_2739': 'DNMT3A', 'gRNA_2747': 'DNMT3A', 'gRNA_2748': 'DNMT3A', 'gRNA_2775': 'DNMT3A', 'gRNA_2776': 'DNMT3A', 'gRNA_2777': 'DNMT3A', 'gRNA_2778': 'DNMT3A', 'gRNA_2784': 'DNMT3A', 'gRNA_2785': 'DNMT3A', 'gRNA_2794': 'DNMT3A', 'gRNA_2802': 'DNMT3A', 'gRNA_2803': 'DNMT3A', 'gRNA_2810': 'DNMT3A', 'gRNA_2842': 'DOT1L', 'gRNA_2891': 'DROSHA', 'gRNA_2892': 'DROSHA', 'gRNA_2914': 'DROSHA', 'gRNA_2917': 'DTX1', 'gRNA_2918': 'DTX1', 'gRNA_2947': 'EED', 'gRNA_2949': 'EED', 'gRNA_2950': 'EED', 'gRNA_2951': 'EED', 'gRNA_2952': 'EED', 'gRNA_2956': 'EED', 'gRNA_2957': 'EED', 'gRNA_2963': 'EGFR', 'gRNA_2971': 'EGFR', 'gRNA_2975': 'EGFR', 'gRNA_2981': 'EGFR', 'gRNA_3011': 'EGFR', 'gRNA_3012': 'EGFR', 'gRNA_3021': 'EGFR', 'gRNA_3025': 'EIF1AX', 'gRNA_3026': 'EIF1AX', 'gRNA_3030': 'EIF1AX', 'gRNA_3031': 'EIF1AX', 'gRNA_3032': 'EIF1AX', 'gRNA_3033': 'EIF1AX', 'gRNA_3034': 'EIF1AX', 'gRNA_3046': 'ELF3', 'gRNA_3047': 'ELF3', 'gRNA_3048': 'ELF3', 'gRNA_3056': 'EP300', 'gRNA_3060': 'EP300', 'gRNA_3061': 'EP300', 'gRNA_3084': 'EP300', 'gRNA_3085': 'EP300', 'gRNA_3086': 'EP300', 'gRNA_3089': 'EP300', 'gRNA_3106': 'EP300', 'gRNA_3107': 'EP300', 'gRNA_3114': 'EP300', 'gRNA_3115': 'EP300', 'gRNA_3142': 'EPHA3', 'gRNA_3143': 'EPHA3', 'gRNA_3220': 'EPHA3', 'gRNA_3221': 'EPHA3', 'gRNA_3224': 'EPHA5', 'gRNA_3225': 'EPHA5', 'gRNA_3249': 'EPHA5', 'gRNA_3250': 'EPHA5', 'gRNA_3251': 'EPHA5', 'gRNA_3283': 'EPHA5', 'gRNA_3313': 'EPHA7', 'gRNA_3314': 'EPHA7', 'gRNA_3340': 'EPHA7', 'gRNA_3341': 'EPHA7', 'gRNA_3383': 'EPHA7', 'gRNA_3415': 'EPHB1', 'gRNA_3416': 'EPHB1', 'gRNA_3469': 'ERBB2', 'gRNA_3470': 'ERBB2', 'gRNA_3471': 'ERBB2', 'gRNA_3502': 'ERBB2', 'gRNA_3503': 'ERBB2', 'gRNA_3510': 'ERBB2', 'gRNA_3511': 'ERBB2', 'gRNA_3515': 'ERBB2', 'gRNA_3516': 'ERBB3', 'gRNA_3517': 'ERBB3', 'gRNA_3518': 'ERBB3', 'gRNA_3522': 'ERBB3', 'gRNA_3523': 'ERBB3', 'gRNA_3524': 'ERBB3', 'gRNA_3525': 'ERBB3', 'gRNA_3543': 'ERBB3', 'gRNA_3544': 'ERBB3', 'gRNA_3545': 'ERBB3', 'gRNA_3569': 'ERBB3', 'gRNA_3570': 'ERBB3', 'gRNA_3571': 'ERBB3', 'gRNA_3572': 'ERBB3', 'gRNA_3577': 'ERBB3', 'gRNA_3578': 'ERBB3', 'gRNA_3579': 'ERBB3', 'gRNA_3580': 'ERBB3', 'gRNA_3626': 'ERBB4', 'gRNA_3666': 'ERCC2', 'gRNA_3676': 'ERCC2', 'gRNA_3677': 'ERCC2', 'gRNA_3679': 'ERCC2', 'gRNA_3680': 'ERCC2', 'gRNA_3681': 'ERCC2', 'gRNA_3682': 'ERCC2', 'gRNA_3685': 'ERCC2', 'gRNA_3686': 'ERCC2', 'gRNA_3692': 'ERCC2', 'gRNA_3693': 'ERCC2', 'gRNA_3694': 'ERCC2', 'gRNA_3698': 'ERCC2', 'gRNA_3699': 'ERCC2', 'gRNA_3703': 'ERCC2', 'gRNA_3704': 'ERCC2', 'gRNA_3705': 'ERCC2', 'gRNA_3711': 'ERCC2', 'gRNA_3712': 'ERCC2', 'gRNA_3754': 'ERCC4', 'gRNA_3755': 'ERCC4', 'gRNA_3804': 'ERG', 'gRNA_3805': 'ERG', 'gRNA_3806': 'ERG', 'gRNA_3838': 'ESR1', 'gRNA_3842': 'ESR1', 'gRNA_3843': 'ESR1', 'gRNA_3861': 'ESR1', 'gRNA_3868': 'ESR1', 'gRNA_3905': 'ETV6', 'gRNA_3906': 'ETV6', 'gRNA_3907': 'ETV6', 'gRNA_3908': 'ETV6', 'gRNA_3909': 'ETV6', 'gRNA_3923': 'ETV6', 'gRNA_3924': 'ETV6', 'gRNA_3925': 'ETV6', 'gRNA_3926': 'ETV6', 'gRNA_3964': 'EZH2', 'gRNA_3975': 'EZH2', 'gRNA_3976': 'EZH2', 'gRNA_3985': 'EZH2', 'gRNA_3995': 'FAS', 'gRNA_3996': 'FAS', 'gRNA_4012': 'FAT1', 'gRNA_4021': 'FAT1', 'gRNA_4032': 'FAT1', 'gRNA_4033': 'FAT1', 'gRNA_4104': 'FBXW7', 'gRNA_4105': 'FBXW7', 'gRNA_4106': 'FBXW7', 'gRNA_4111': 'FBXW7', 'gRNA_4116': 'FBXW7', 'gRNA_4117': 'FBXW7', 'gRNA_4118': 'FBXW7', 'gRNA_4119': 'FBXW7', 'gRNA_4141': 'FBXW7', 'gRNA_4142': 'FBXW7', 'gRNA_4143': 'FBXW7', 'gRNA_4144': 'FBXW7', 'gRNA_4191': 'FGF4', 'gRNA_4192': 'FGF4', 'gRNA_4193': 'FGF4', 'gRNA_4194': 'FGF4', 'gRNA_4195': 'FGF4', 'gRNA_4213': 'FGFR1', 'gRNA_4225': 'FGFR1', 'gRNA_4226': 'FGFR1', 'gRNA_4246': 'FGFR2', 'gRNA_4247': 'FGFR2', 'gRNA_4248': 'FGFR2', 'gRNA_4261': 'FGFR2', 'gRNA_4262': 'FGFR2', 'gRNA_4263': 'FGFR2', 'gRNA_4302': 'FGFR3', 'gRNA_4303': 'FGFR3', 'gRNA_4304': 'FGFR3', 'gRNA_4329': 'FGFR3', 'gRNA_4330': 'FGFR3', 'gRNA_4331': 'FGFR3', 'gRNA_4357': 'FGFR4', 'gRNA_4419': 'FLT1', 'gRNA_4421': 'FLT1', 'gRNA_4422': 'FLT1', 'gRNA_4440': 'FLT3', 'gRNA_4447': 'FLT3', 'gRNA_4459': 'FLT3', 'gRNA_4460': 'FLT3', 'gRNA_4461': 'FLT3', 'gRNA_4547': 'FOXA1', 'gRNA_4548': 'FOXA1', 'gRNA_4549': 'FOXA1', 'gRNA_4550': 'FOXA1', 'gRNA_4562': 'FOXA1', 'gRNA_4567': 'FOXA1', 'gRNA_4577': 'FOXA1', 'gRNA_4578': 'FOXA1', 'gRNA_4586': 'FOXA1', 'gRNA_4587': 'FOXA1', 'gRNA_4589': 'FOXA1', 'gRNA_4590': 'FOXA1', 'gRNA_4591': 'FOXA1', 'gRNA_4621': 'FOXO1', 'gRNA_4622': 'FOXO1', 'gRNA_4627': 'FOXO1', 'gRNA_4628': 'FOXO1', 'gRNA_4665': 'FOXP1', 'gRNA_4704': 'FYN', 'gRNA_4734': 'GATA2', 'gRNA_4735': 'GATA2', 'gRNA_4770': 'GATA3', 'gRNA_4782': 'GATA3', 'gRNA_4783': 'GATA3', 'gRNA_4826': 'GLI1', 'gRNA_4827': 'GLI1', 'gRNA_4828': 'GLI1', 'gRNA_4829': 'GLI1', 'gRNA_4858': 'GNA13', 'gRNA_4884': 'GNAS', 'gRNA_4885': 'GNAS', 'gRNA_4888': 'GNAS', 'gRNA_4889': 'GNAS', 'gRNA_4893': 'GNB1', 'gRNA_4894': 'GNB1', 'gRNA_4961': 'GRIN2A', 'gRNA_4969': 'GRIN2A', 'gRNA_5176': 'HRAS', 'gRNA_5194': 'IDH2', 'gRNA_5227': 'IGF1R', 'gRNA_5228': 'IGF1R', 'gRNA_5229': 'IGF1R', 'gRNA_5236': 'IGF1R', 'gRNA_5237': 'IGF1R', 'gRNA_5319': 'IKZF1', 'gRNA_5372': 'INHA', 'gRNA_5373': 'INHA', 'gRNA_5374': 'INHA', 'gRNA_5454': 'INPP4A', 'gRNA_5455': 'INPP4A', 'gRNA_5456': 'INPP4A', 'gRNA_5477': 'INPP4A', 'gRNA_5501': 'INPPL1', 'gRNA_5509': 'INPPL1', 'gRNA_5561': 'INSR', 'gRNA_5614': 'IRF4', 'gRNA_5615': 'IRF4', 'gRNA_5618': 'IRF8', 'gRNA_5620': 'IRF8', 'gRNA_5621': 'IRF8', 'gRNA_5623': 'IRS1', 'gRNA_5624': 'IRS1', 'gRNA_5625': 'IRS1', 'gRNA_5626': 'IRS1', 'gRNA_5627': 'IRS1', 'gRNA_5628': 'IRS1', 'gRNA_5740': 'JAK1', 'gRNA_5741': 'JAK1', 'gRNA_5742': 'JAK1', 'gRNA_5769': 'JAK2', 'gRNA_5772': 'JAK2', 'gRNA_5773': 'JAK2', 'gRNA_5776': 'JAK2', 'gRNA_5777': 'JAK2', 'gRNA_5792': 'JAK3', 'gRNA_5854': 'KDM5C', 'gRNA_5860': 'KDM5C', 'gRNA_5861': 'KDM5C', 'gRNA_5864': 'KDM5C', 'gRNA_5865': 'KDM5C', 'gRNA_5912': 'KDM6A', 'gRNA_6000': 'KDR', 'gRNA_6063': 'KEAP1', 'gRNA_6064': 'KEAP1', 'gRNA_6080': 'KEAP1', 'gRNA_6081': 'KEAP1', 'gRNA_6086': 'KEAP1', 'gRNA_6087': 'KEAP1', 'gRNA_6103': 'KIT', 'gRNA_6104': 'KIT', 'gRNA_6105': 'KIT', 'gRNA_6109': 'KIT', 'gRNA_6110': 'KIT', 'gRNA_6111': 'KIT', 'gRNA_6112': 'KIT', 'gRNA_6113': 'KIT', 'gRNA_6117': 'KIT', 'gRNA_6125': 'KIT', 'gRNA_6134': 'KLF4', 'gRNA_6135': 'KLF4', 'gRNA_6257': 'KMT2B', 'gRNA_6265': 'KMT2B', 'gRNA_6266': 'KMT2B', 'gRNA_6383': 'KMT2C', 'gRNA_6384': 'KMT2C', 'gRNA_6472': 'KMT2D', 'gRNA_6473': 'KMT2D', 'gRNA_6479': 'KMT2D', 'gRNA_6480': 'KMT2D', 'gRNA_6487': 'KMT2D', 'gRNA_6488': 'KMT2D', 'gRNA_6525': 'KMT2D', 'gRNA_6526': 'KMT2D', 'gRNA_6527': 'KMT2D', 'gRNA_6604': 'KMT2D', 'gRNA_6629': 'KMT2D', 'gRNA_6712': 'KRAS', 'gRNA_6717': 'KRAS', 'gRNA_6743': 'LATS1', 'gRNA_6744': 'LATS1', 'gRNA_6745': 'LATS1', 'gRNA_6759': 'LATS1', 'gRNA_6781': 'LCK', 'gRNA_6782': 'LCK', 'gRNA_6797': 'LYN', 'gRNA_6829': 'MAP2K1', 'gRNA_6830': 'MAP2K1', 'gRNA_6831': 'MAP2K1', 'gRNA_6832': 'MAP2K1', 'gRNA_6833': 'MAP2K1', 'gRNA_6834': 'MAP2K1', 'gRNA_6835': 'MAP2K1', 'gRNA_6837': 'MAP2K1', 'gRNA_6841': 'MAP2K1', 'gRNA_6842': 'MAP2K1', 'gRNA_6848': 'MAP2K2', 'gRNA_6849': 'MAP2K2', 'gRNA_6888': 'MAP2K4', 'gRNA_6889': 'MAP2K4', 'gRNA_6890': 'MAP2K4', 'gRNA_6894': 'MAP2K4', 'gRNA_6895': 'MAP2K4', 'gRNA_6912': 'MAP3K1', 'gRNA_6913': 'MAP3K1', 'gRNA_6914': 'MAP3K1', 'gRNA_6915': 'MAP3K1', 'gRNA_6992': 'MAX', 'gRNA_7029': 'MED12', 'gRNA_7143': 'MET', 'gRNA_7144': 'MET', 'gRNA_7148': 'MET', 'gRNA_7150': 'MET', 'gRNA_7152': 'MET', 'gRNA_7170': 'MGA', 'gRNA_7171': 'MGA', 'gRNA_7188': 'MGA', 'gRNA_7203': 'MGA', 'gRNA_7204': 'MGA', 'gRNA_7205': 'MGA', 'gRNA_7214': 'MITF', 'gRNA_7264': 'MLH1', 'gRNA_7308': 'MSH3', 'gRNA_7309': 'MSH3', 'gRNA_7310': 'MSH3', 'gRNA_7384': 'MTOR', 'gRNA_7392': 'MTOR', 'gRNA_7393': 'MTOR', 'gRNA_7428': 'MTOR', 'gRNA_7429': 'MTOR', 'gRNA_7430': 'MTOR', 'gRNA_7467': 'MTOR', 'gRNA_7468': 'MTOR', 'gRNA_7473': 'MTOR', 'gRNA_7478': 'MTOR', 'gRNA_7479': 'MTOR', 'gRNA_7481': 'MYC', 'gRNA_7482': 'MYC', 'gRNA_7509': 'MYD88', 'gRNA_7510': 'MYD88', 'gRNA_7511': 'MYD88', 'gRNA_7512': 'MYD88', 'gRNA_7513': 'MYD88', 'gRNA_7514': 'MYD88', 'gRNA_7557': 'NCOA3', 'gRNA_7558': 'NCOA3', 'gRNA_7602': 'NCOR1', 'gRNA_7627': 'NEGR1', 'gRNA_7664': 'NF1', 'gRNA_7667': 'NF1', 'gRNA_7683': 'NF1', 'gRNA_7684': 'NF1', 'gRNA_7765': 'NF1', 'gRNA_7787': 'NF2', 'gRNA_7812': 'NFE2', 'gRNA_7813': 'NFE2', 'gRNA_7814': 'NFE2', 'gRNA_7815': 'NFE2L2', 'gRNA_7816': 'NFE2L2', 'gRNA_7822': 'NFE2L2', 'gRNA_7823': 'NFE2L2', 'gRNA_7826': 'NFE2L2', 'gRNA_7827': 'NFE2L2', 'gRNA_7828': 'NFE2L2', 'gRNA_7829': 'NFE2L2', 'gRNA_7839': 'NKX2-1', 'gRNA_7843': 'NKX2-1', 'gRNA_7873': 'NKX3-1', 'gRNA_7885': 'NOTCH1', 'gRNA_7886': 'NOTCH1', 'gRNA_7901': 'NOTCH1', 'gRNA_7902': 'NOTCH1', 'gRNA_7917': 'NOTCH1', 'gRNA_7918': 'NOTCH1', 'gRNA_7919': 'NOTCH1', 'gRNA_7935': 'NOTCH1', 'gRNA_7956': 'NOTCH1', 'gRNA_8028': 'NOTCH2', 'gRNA_8198': 'NOTCH3', 'gRNA_8216': 'NPM1', 'gRNA_8217': 'NRAS', 'gRNA_8225': 'NRAS', 'gRNA_8226': 'NSD1', 'gRNA_8227': 'NSD1', 'gRNA_8228': 'NSD1', 'gRNA_8241': 'NSD1', 'gRNA_8302': 'NTRK2', 'gRNA_8366': 'NTRK3', 'gRNA_8367': 'NTRK3', 'gRNA_8409': 'NTRK3', 'gRNA_8410': 'NTRK3', 'gRNA_8493': 'PAX5', 'gRNA_8494': 'PAX5', 'gRNA_8513': 'PAX5', 'gRNA_8569': 'PDGFRA', 'gRNA_8650': 'PDGFRB', 'gRNA_8651': 'PDGFRB', 'gRNA_8652': 'PDGFRB', 'gRNA_8668': 'PDGFRB', 'gRNA_8672': 'PDGFRB', 'gRNA_8673': 'PDGFRB', 'gRNA_8695': 'PHF6', 'gRNA_8696': 'PHF6', 'gRNA_8699': 'PHF6', 'gRNA_8775': 'PIK3CA', 'gRNA_8782': 'PIK3CA', 'gRNA_8783': 'PIK3CA', 'gRNA_8784': 'PIK3CA', 'gRNA_8789': 'PIK3CA', 'gRNA_8790': 'PIK3CA', 'gRNA_8791': 'PIK3CA', 'gRNA_8793': 'PIK3CA', 'gRNA_8794': 'PIK3CA', 'gRNA_8795': 'PIK3CA', 'gRNA_8803': 'PIK3CA', 'gRNA_8804': 'PIK3CA', 'gRNA_8808': 'PIK3CA', 'gRNA_8813': 'PIK3CA', 'gRNA_8814': 'PIK3CA', 'gRNA_8824': 'PIK3CA', 'gRNA_8825': 'PIK3CA', 'gRNA_8826': 'PIK3CA', 'gRNA_8827': 'PIK3CA', 'gRNA_8831': 'PIK3CA', 'gRNA_8833': 'PIK3CA', 'gRNA_8834': 'PIK3CA', 'gRNA_8835': 'PIK3CA', 'gRNA_8840': 'PIK3CA', 'gRNA_8841': 'PIK3CA', 'gRNA_8852': 'PIK3CA', 'gRNA_8854': 'PIK3CA', 'gRNA_8855': 'PIK3CA', 'gRNA_8857': 'PIK3CA', 'gRNA_8858': 'PIK3CA', 'gRNA_8861': 'PIK3CA', 'gRNA_8862': 'PIK3CA', 'gRNA_8867': 'PIK3CA', 'gRNA_8868': 'PIK3CA', 'gRNA_8869': 'PIK3CA', 'gRNA_8891': 'PIK3CB', 'gRNA_8893': 'PIK3CB', 'gRNA_8895': 'PIK3CB', 'gRNA_8896': 'PIK3CB', 'gRNA_8897': 'PIK3CB', 'gRNA_8935': 'PIK3CD', 'gRNA_8936': 'PIK3CD', 'gRNA_8997': 'PIK3CG', 'gRNA_8998': 'PIK3CG', 'gRNA_8999': 'PIK3CG', 'gRNA_9000': 'PIK3CG', 'gRNA_9037': 'PIK3R1', 'gRNA_9041': 'PIK3R1', 'gRNA_9055': 'PIK3R1', 'gRNA_9056': 'PIK3R1', 'gRNA_9063': 'PIK3R1', 'gRNA_9064': 'PIK3R1', 'gRNA_9084': 'PIK3R2', 'gRNA_9085': 'PIK3R2', 'gRNA_9105': 'PIK3R2', 'gRNA_9114': 'PIK3R3', 'gRNA_9115': 'PIK3R3', 'gRNA_9116': 'PIK3R3', 'gRNA_9286': 'PMS2', 'gRNA_9392': 'POLE', 'gRNA_9410': 'POT1', 'gRNA_9411': 'POT1', 'gRNA_9513': 'PRDM1', 'gRNA_9611': 'PRKD1', 'gRNA_9612': 'PRKD1', 'gRNA_9624': 'PRKD1', 'gRNA_9625': 'PRKD1', 'gRNA_9703': 'PTPN1', 'gRNA_9705': 'PTPN11', 'gRNA_9706': 'PTPN11', 'gRNA_9730': 'PTPN11', 'gRNA_9744': 'PTPN11', 'gRNA_9745': 'PTPN11', 'gRNA_9838': 'PTPRD', 'gRNA_9875': 'PTPRD', 'gRNA_9876': 'PTPRD', 'gRNA_9881': 'PTPRD', 'gRNA_10049': 'PTPRT', 'gRNA_10106': 'PTPRT', 'gRNA_10107': 'PTPRT', 'gRNA_10117': 'PTPRT', 'gRNA_10118': 'PTPRT', 'gRNA_10150': 'PTPRT', 'gRNA_10274': 'RAD21', 'gRNA_10275': 'RAD21', 'gRNA_10306': 'RAD51C', 'gRNA_10307': 'RAD51C', 'gRNA_10336': 'RAF1', 'gRNA_10337': 'RAF1', 'gRNA_10342': 'RAF1', 'gRNA_10343': 'RAF1', 'gRNA_10363': 'RARA', 'gRNA_10378': 'RARA', 'gRNA_10379': 'RARA', 'gRNA_10380': 'RARA', 'gRNA_10397': 'RASA1', 'gRNA_10406': 'RASA1', 'gRNA_10436': 'RB1', 'gRNA_10437': 'RB1', 'gRNA_10447': 'RB1', 'gRNA_10448': 'RB1', 'gRNA_10456': 'RB1', 'gRNA_10466': 'RB1', 'gRNA_10467': 'RB1', 'gRNA_10468': 'RB1', 'gRNA_10504': 'RBM10', 'gRNA_10546': 'RBM10', 'gRNA_10547': 'RBM10', 'gRNA_10548': 'RBM10', 'gRNA_10571': 'RECQL', 'gRNA_10572': 'RECQL', 'gRNA_10573': 'RECQL', 'gRNA_10574': 'RECQL', 'gRNA_10595': 'RET', 'gRNA_10596': 'RET', 'gRNA_10597': 'RET', 'gRNA_10598': 'RET', 'gRNA_10617': 'RHEB', 'gRNA_10618': 'RHEB', 'gRNA_10622': 'RHOA', 'gRNA_10623': 'RHOA', 'gRNA_10632': 'RHOA', 'gRNA_10633': 'RHOA', 'gRNA_10634': 'RHOA', 'gRNA_10635': 'RHOA', 'gRNA_10636': 'RHOA', 'gRNA_10637': 'RHOA', 'gRNA_10656': 'RICTOR', 'gRNA_10657': 'RICTOR', 'gRNA_10664': 'RICTOR', 'gRNA_10665': 'RICTOR', 'gRNA_10679': 'RIT1', 'gRNA_10680': 'RIT1', 'gRNA_10681': 'RIT1', 'gRNA_10684': 'RIT1', 'gRNA_10690': 'RNF43', 'gRNA_10770': 'ROS1', 'gRNA_10909': 'RTEL1', 'gRNA_10910': 'RTEL1', 'gRNA_10929': 'RUNX1', 'gRNA_10930': 'RUNX1', 'gRNA_10932': 'RUNX1', 'gRNA_10955': 'RUNX1', 'gRNA_10969': 'RUNX1', 'gRNA_10970': 'RUNX1', 'gRNA_10971': 'RUNX1', 'gRNA_11017': 'SDHA', 'gRNA_11018': 'SDHA', 'gRNA_11069': 'SETBP1', 'gRNA_11070': 'SETBP1', 'gRNA_11071': 'SETBP1', 'gRNA_11098': 'SETD2', 'gRNA_11099': 'SETD2', 'gRNA_11111': 'SETD2', 'gRNA_11112': 'SETD2', 'gRNA_11113': 'SETD2', 'gRNA_11114': 'SETD2', 'gRNA_11122': 'SETD6', 'gRNA_11132': 'SF3B1', 'gRNA_11133': 'SF3B1', 'gRNA_11136': 'SF3B1', 'gRNA_11141': 'SF3B1', 'gRNA_11142': 'SF3B1', 'gRNA_11143': 'SF3B1', 'gRNA_11144': 'SF3B1', 'gRNA_11157': 'SF3B1', 'gRNA_11158': 'SF3B1', 'gRNA_11159': 'SF3B1', 'gRNA_11169': 'SF3B1', 'gRNA_11182': 'SH2B3', 'gRNA_11195': 'SHQ1', 'gRNA_11208': 'SMAD2', 'gRNA_11209': 'SMAD2', 'gRNA_11218': 'SMAD2', 'gRNA_11219': 'SMAD2', 'gRNA_11223': 'SMAD2', 'gRNA_11224': 'SMAD2', 'gRNA_11284': 'SMAD4', 'gRNA_11285': 'SMAD4', 'gRNA_11298': 'SMAD4', 'gRNA_11305': 'SMAD4', 'gRNA_11306': 'SMAD4', 'gRNA_11312': 'SMAD4', 'gRNA_11315': 'SMAD4', 'gRNA_11319': 'SMAD4', 'gRNA_11322': 'SMAD4', 'gRNA_11323': 'SMAD4', 'gRNA_11324': 'SMAD4', 'gRNA_11325': 'SMAD4', 'gRNA_11326': 'SMAD4', 'gRNA_11336': 'SMAD4', 'gRNA_11337': 'SMAD4', 'gRNA_11449': 'SMARCA4', 'gRNA_11450': 'SMARCA4', 'gRNA_11454': 'SMARCA4', 'gRNA_11499': 'SMARCA4', 'gRNA_11500': 'SMARCA4', 'gRNA_11532': 'SMARCA4', 'gRNA_11533': 'SMARCA4', 'gRNA_11581': 'SMC1A', 'gRNA_11582': 'SMC1A', 'gRNA_11589': 'SMC3', 'gRNA_11590': 'SMG1', 'gRNA_11607': 'SMO', 'gRNA_11608': 'SMO', 'gRNA_11609': 'SMO', 'gRNA_11670': 'SOCS1', 'gRNA_11671': 'SOCS1', 'gRNA_11689': 'SOS1', 'gRNA_11701': 'SOS1', 'gRNA_11702': 'SOS1', 'gRNA_11703': 'SOS1', 'gRNA_11748': 'SOX2', 'gRNA_11796': 'SOX9', 'gRNA_11797': 'SOX9', 'gRNA_11798': 'SOX9', 'gRNA_11967': 'STAG2', 'gRNA_11968': 'STAG2', 'gRNA_11992': 'STAT3', 'gRNA_11993': 'STAT3', 'gRNA_11994': 'STAT3', 'gRNA_12001': 'STAT3', 'gRNA_12002': 'STAT3', 'gRNA_12006': 'STAT3', 'gRNA_12007': 'STAT3', 'gRNA_12024': 'STAT3', 'gRNA_12025': 'STAT3', 'gRNA_12026': 'STAT3', 'gRNA_12062': 'STAT6', 'gRNA_12063': 'STAT6', 'gRNA_12064': 'STAT6', 'gRNA_12065': 'STAT6', 'gRNA

,sgRNA,gene,D0_preEPO_rep1,D0_preEPO_rep2,D0_preEPO_rep3,D3_rep2,D3_rep3,D5_noPuro_rep1,D5_noPuro_rep2,D5_noPuro_rep3,D5_puro_rep1,D5_puro_rep2,D5_puro_rep3,D15_noPuro_rep1,D15_noPuro_rep2,D15_noPuro_rep3,D15_puro_rep1,D15_puro_rep2,D15_puro_rep3
0,gRNA_1,ABL1,3271.0,4002.0,3449.0,3063.0,5311.0,4440.0,4417.0,2419.0,3444.0,4838.0,2579.0,4986.0,3397.0,3280.0,2378.0,2295.0,2903.0
1,gRNA_2,ABL1,963.0,1241.0,879.0,2536.0,3586.0,2709.0,2791.0,1449.0,2670.0,4262.0,1894.0,1769.0,1308.0,1100.0,1352.0,557.0,655.0
2,gRNA_3,ABL1,1914.0,2102.0,1828.0,3187.0,4283.0,3402.0,3432.0,1929.0,2658.0,4051.0,2089.0,3899.0,2042.0,2291.0,1982.0,1713.0,1880.0
3,gRNA_67,AGO2,2147.0,1938.0,2189.0,3674.0,2576.0,2443.0,2343.0,1557.0,2115.0,3380.0,2362.0,1357.0,909.0,841.0,655.0,639.0,548.0
4,gRNA_84,AKT1,28663.0,27697.0,7336.0,23349.0,22093.0,13262.0,21993.0,11535.0,13180.0,16743.0,12417.0,21964.0,12916.0,13077.0,8989.0,9483.0,12326.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1065,gRNA_13604,controlsgRNA,30467.0,30615.0,18579.0,18333.0,19719.0,14913.0,22348.0,10267.0,13505.0,19231.0,14054.0,30553.0,13120.0,14259.0,11951.0,11315.0,14722.0
1066,gRNA_13605,controlsgRNA,12679.0,13332.0,7547.0,5166.0,8568.0,4087.0,7456.0,5165.0,5329.0,8375.0,6138.0,13771.0,4087.0,5664.0,4227.0,3517.0,5259.0
1067,gRNA_13606,controlsgRNA,50781.0,53566.0,24407.0,19358.0,19493.0,14310.0,29767.0,16994.0,17364.0,28438.0,28339.0,41648.0,22720.0,23874.0,16749.0,23209.0,23078.0
1068,gRNA_13607,controlsgRNA,26689.0,26676.0,13389.0,11723.0,11537.0,7951.0,13292.0,8560.0,9589.0,13902.0,6733.0,17044.0,9112.0,11379.0,8432.0,8798.0,11886.0
1069,gRNA_13608,controlsgRNA,5656.0,5616.0,2778.0,3386.0,2626.0,1933.0,3212.0,2132.0,2629.0,4269.0,2105.0,4170.0,2989.0,3795.0,3099.0,2531.0,3529.0

In [45]:
#and finally save it for running on mageck

join_out.to_csv('/net/bmc-lab2/data/lab/sanchezrivera/hcevasco/DASIT/251212San/guide_counts_ABE_DASIT.txt', sep='\t', index=False)

In [46]:
os.getcwd()

'/net/bmc-lab2/data/lab/sanchezrivera/hcevasco'